INSERT INTO easywords(ID, Word, Meaning, Category) VALUES
(1,'abilitare','Autorizzare, rendere abile qualcuno ad una professione.',''),
(2,'dovere','Essere obbligati, tenuti a fare qualcosa.',''),
(3,'piazza','Spazio urbano di forma variabile.',''),
(4,'visore','Apparecchio per esaminare in trasparenza lastre fotografiche.',''),
(5,'gioia',"Sentimento di piena e viva soddisfazione dell'animo",''),
(6,'banda','Gruppo di musicisti.',''),
(7,'potere','Essere in grado di fare qualcosa, avendone la capacità.',''),
(8,'sottile','Di spessore o diametro ridotto e comunque inferiore alla media.',''),
(9,'affermare','Dire qualcosa con sicurezza.',''),
(10,'carta','Materiale igroscopico.',''),
(11,'cultura','Insieme di conoscenze.',''),
(12,'esame','Attenta considerazione di qualcosa.',''),
(13,'ombra','La figura che un corpo opaco proietta su una superficie e che ne riproduce la forma.',''),
(14,'giocare','Attività fatta da una o più persone per divertimento.',''),
(15,'bambina',"L'essere umano nell'età che va dalla nascita all'inizio della fanciullezza.",''),
(16,'percentuale',"Descrive la grandezza di una quantità rispetto ad un'altra.",''),
(17,'pantalone','Indumento unisex che copre dalla vita in giù',''),
(18,'sostituto',"Persona che ne sostituisce un'altra in una determinata funzione.",''),
(19,'cadere','Finire a terra.',''),
(20,'dolce','Che è gradevole al gusto, che non è né amaro né amaro.',''),
(21,'pezzo','Porzione di dimensioni variabili di un materiale solido.',''),
(22,'paradiso','Luogo raggiunto dalle anime dei giusti dopo la morte.',''),
(23,'scegliere','Prendere una decisione da uno o più cose.',''),
(24,'migliore','La persona più capace, più abile.',''),
(25,'portare','Trasportare qualcosa o qualcuno reggendolo su di sé.',''),
(26,'verde',"Del colore che sta tra il giallo e l'azzurro ed è caratteristico dell'erba.",''),
(27,'ovunque','In qualsiasi posto, dappertutto.',''),
(28,'faccia',"Parte anteriore della testa dell'uomo.",''),
(29,'costringere','Indurre, obbligare, spingere qualcuno a fare qualcosa.',''),
(30,'abbiate','',''),
(31,'abbronzare','Far diventare qualcosa del colore del bronzo.',''),
(32,'chiudere','Mettere a contatto le parti disgiunte o aperte di un oggetto.',''),
(33,'abilitare','Autorizzare, rendere abile qualcuno a una professione.',''),
(34,'battere','Percuotere ripetutamente qualcosa.',''),
(35,'aiutare','Soccorrere qualcuno in difficoltà.',''),
(36,'aspettare',"Essere o restare in attesa dell'arrivo di qualcuno o del verificarsi di qualcosa.",''),
(37,'rimanere','Restare da qualche parte.',''),
(38,'lavandino','Vaschetta di ceramica collocata in genere nella stanza da bagno.',''),
(39,'ospitare','Accogliere qualcuno come ospite.',''),
(40,'esempio','Qualunque cosa o persona che possa essere presa come modello.',''),
(41,'tastiera',"Periferica di input destinata all'inserimento manuale di dati.",''),
(42,'nascere','Venire alla luce.',''),
(43,'congelatore','Dispositivo dei frigoriferi per produrre e mantenere una bassa temperatura.',''),
(44,'giallo',"Il giallo è uno dei colori dello spettro che l'uomo riesce a vedere.",''),
(45,'legno','Insieme di tessuti che costituiscono il tronco, i rami e le radici di alberi.',''),
(46,'crociera','Navigazione di una o più navi, circoscritta a un dato tratto di mare.',''),
(47,'lavanda','Olio che viene estratto da una pianta usata in terapia.',''),
(48,'potere','Essere in grado di fare qualcosa, avendone la capacità.',''),
(49,'autore','Chi crea, causa, determina qualcosa.',''),
(50,'carattere','Complesso di qualità psicologiche che costituiscono la personalità.',''),
(51,'pedana','Elemento rialzato, perlopiù in legno, che isola o innalza dal pavimento.',''),
(52,'ritrovare','Trovare qualcosa o qualcuno che si era smarrito.',''),
(53,'lavare','Rendere pulito qualcosa usando acqua.',''),
(54,'accarezzare','Fare carezze, lisciare con la mano qualcuno o qualcosa.',''),
(55,'sicuro','Che non comporta o non corre pericoli.',''),
(56,'poltrona','Sedile ampio e comodo, bene imbottito e munito di braccioli.',''),
(57,'genere','Insieme delle caratteristiche fondamentali che contraddistinguono una categoria.',''),
(58,'campo','Porzione di terreno coltivato o adibito a pascolo.',''),
(59,'figlio','Creatura umana rispetto a coloro che lo hanno generato.',''),
(60,'detersivo','Prodotto di uso domestico per il lavaggio di tessuti.',''),
(61,'estero','Che è fuori dai confini di uno stato o che da lì proviene.',''),
(62,'odore',"Sensazione trasmessa dall'olfatto.",''),
(63,'padella','Utensile da cucina in metallo, tondo e basso, provvisto di un lungo manico.',''),
(64,'batteria',"Gruppo di fuoco dell'artiglieria costituito da quattro o sei pezzi di uguale calibro. ",''),
(65,'margine','Parte estrema di una cosa.',''),
(66,'pompa','Allestimento solenne e fastoso approntato in occasione di cerimonie o feste.',''),
(67,'gruccia','Accessorio usato per reggere abiti.',''),
(68,'panchina',"Sedile per più persone posto all'aperto e fissato al terreno.",''),
(69,'carta','Materiale igroscopico, costituito da materie prime prevalentemente vegetali.',''),
(70,'voglia','Impulso a soddisfare un desiderio o un bisogno.',''),
(71,'abboccare',"Detto dei pesci, afferrare l'esca.",''),
(72,'accentrare','Riunire nello stesso luogo persone o servizi.',''),
(73,'conoscere','Possedere le nozioni e le esperienze necessarie.',''),
(74,'caffettiera','Recipiente per la preparazione del caffè.',''),
(75,'ricetta','Insieme di istruzioni per compiere un procedimento di trasformazione in generale.',''),
(76,'parola','Unità linguistica costituita da un insieme di suoni rappresentabili graficamente.',''),
(77,'orticante','Provoca al contatto una sensazione di irritazione o di forte bruciore sulla cute.',''),
(78,'usare','Fare uso, servirsi di qualcosa.',''),
(79,'volere','Essere intenzionato a ottenere qualcosa.',''),
(80,'diamante','Materiale simbolo della limpidezza.',''),
(81,'errore','Allontanamento dai principi logici.',''),
(82,'donna','Persona adulta di sesso femminile.',''),
(83,'latte','Liquido bianco opaco prodotto per secrezione dalle ghiandole mammarie delle femmine dei mammiferi.',''),
(84,'animale','Sono un regno del dominio degli eucarioti.',''),
(85,'avere','Essere in possesso di beni materiali.',''),
(86,'sorriso','Riso appena accennato, con un lieve movimento delle labbra.',''),
(87,'pranzo','Il pasto che viene consumato intorno a mezzogiorno.',''),
(88,'aderenza','Coesione perfetta tra due superfici combacianti.',''),
(89,'scoprire','Togliere ciò che copre una cosa.',''),
(90,'piano','Che è privo di rilievi, sporgenze.',''),
(91,'mobile','Che può essere mosso, spostato.',''),
(92,'stato','Condizione, modo di essere o di trovarsi.',''),
(93,'superiore','Che sta più in alto, che sta sopra.',''),
(94,'basso','Di altezza non elevata o inferiore alla media.',''),
(95,'consigliare',' Suggerire qqualcosa a qualcuno',''),
(96,'presenza','Fatto che una persona si trovi in un luogo.',''),
(97,'fortuna','Sorte buona o cattiva.',''),
(98,'piscina',"Vasca piena d'acqua adibita a vari usi.",''),
(99,'accettato','Ricevuto qualcosa con pieno consenso.',''),
(100,'lotta','Scontro violento fra due parti.',''),
(101,'abitabile','Che si può abitare.',''),
(102,'tornare','Presentarsi, manifestarsi di nuovo.',''),
(103,'tenere','Trattenere, afferrare qualcuno o qualcosa.',''),
(104,'piantare','Mettere nella terra semi o piantine perché attecchiscano.',''),
(105,'pieno','Che è stato riempito in modo da non poter più contenere nulla.',''),
(106,'arrivare','Manifestarsi, presentarsi.',''),
(107,'legare','Avvolgere strettamente qualcuno o qualcosa.',''),
(108,'secolo','Periodo di tempo di cento anni.',''),
(109,'pacchetto','Confezione, involucro di piccole dimensioni.',''),
(110,'scuola','Istituzione educativa che ha il compito di insegnare.',''),
(111,'musica','Arte e tecnica della combinazione dei suoni.',''),
(112,'accordare',"Mettere d'accordo due o più cose o persone",''),
(113,'perfetto','Completo, compiuto in tutte le sue parti.',''),
(114,'olfattivo','Senso che permette di percepire e distinguere gli odori.',''),
(115,'pilota','Chi guida un mezzo per il quale occorre una preparazione speciale.',''),
(116,'parare','Addobbare, ornare qualcosa con i paramenti.',''),
(117,'politica',"Arte, scienza del governo e dell'amministrazione dello Stato.",''),
(118,'armare','Fornire qualcuno di armi.',''),
(119,'teatro','Costruzione adibita alla rappresentazione di opere drammatiche.',''),
(120,'parrucca','Capigliatura posticcia, di capelli veri o finti.',''),
(121,'piumino','Piuma degli uccelli.',''),
(122,'acquistare','Ottenere la proprietà di qualcosa mediante pagamento ',''),
(123,'dirigere','Rivolgere qualcosa in una direzione.',''),
(124,'pericolo','Probabilità di danno, possibilità di evento rischioso.',''),
(125,'ricco','Che dispone di beni e mezzi economici in abbondanza.',''),
(126,'ostentare','Esporre qualcosa con insistenza e vanto.',''),
(127,'secondo','Numero cardinale due.',''),
(128,'servizio','Prestazione di lavoro domestico in case private.',''),
(129,'tovaglia','Capo di tessuto o di plastica che si stende sulla tavola.',''),
(130,'ambiente','Spazio e complesso delle condizioni che consentono la vita.',''),
(131,'paracadute',"Dispositivo per frenare la caduta di un corpo nell'aria.",''),
(132,'partecipare','Prendere parte a qualcosa.',''),
(133,'panettone','Dolce natalizio.',''),
(134,'scoppiare','Spaccarsi improvvisamente in più pezzi.',''),
(135,'nastro','Striscia di tessuto, solitamente usata per guarnizioni e orlature.',''),
(136,'lampadario', "Apparecchio per l'illuminazione artificiale.",''),
(137,'borsa','Mercato dove vengono scambiati valori mobiliari.',''),
(138,'stanza','Ambienti interni di un edificio.',''),
(139,'pedata','Impronta, orma lasciata dal piede.',''),
(140,'contenere','Tenere dentro di sé, racchiudere qualcosa.',''),
(141,'purgatorio','Lo stato temporaneo di espiazione cui sono assoggettate le anime',''),
(142,'ricerca','Attività finalizzata a trovare o scoprire qualcuno o qualcosa.',''),
(143,'fresco','Di un freddo moderato e piacevole.',''),
(144,'adorazione','Venerare una divinità.',''),
(145,'togliere','Levare via qualcuno o qualcosa da un posto.',''),
(146,'testa',"Parte del corpo, superiore nell'uomo.",''),
(147,'vestire','Coprire qualcosa con abiti.',''),
(148,'correre','Andare velocemente.',''),
(149,'scendere','Fermarsi in un posto durante o dopo un viaggio.',''),
(150,'palato','Privo di peli o di capelli.',''),
(151,'parlare','Articolare suoni, manifestare con la voce la facoltà del linguaggio.',''),
(152,'foresta','Vasta zona non antropizzata dove la vegetazione naturale.',''),
(153,'cartello','Accordo tra più produttori indipendenti di un bene.',''),
(154,'camera','Ambiente abitativo in una casa.',''),
(155,'parere','Sembrare a qualcuno in maniera non certa.',''),
(156,'pietra','Massa di roccia compatta.',''),
(157,'avvenire','Detto di un evento, avere luogo.',''),
(158,'parallelo','Rette complanari che non hanno punti in comune.',''),
(159,'detergente','Miscela di sostanze chimiche per rimuovere lo sporco.',''),
(160,'commercio','Attività consistente nel comperare e vendere prodotti.',''),
(161,'scappare','Fuggire da un certo posto.',''),
(162,'contrario','Che è in opposizione a qualcosa o a qualcuno.',''),
(163,'rendere',"Restituire, riconsegnare qualcosa a qualcuno che l'ha perso ",''),
(164,'pentirsi','Provare rimorso per qualcosa di male che si è compiuto.',''),
(165,'osteggiare','Ostacolare, contrastare qualcuno o qualcosa.',''),
(166,'bilancia','Strumento usato per misurare il peso di un corpo.',''),
(167,'baratto','Scambiare un oggetto con un altro.',''),
(168,'normale','Riferibile alla norma, alla consuetudine.',''),
(169,'fabbrica','Luogo di produzione di manufatti industriali.',''),
(170,'sigaretta','Cilindretto di carta sottile contenente tabacco trinciato.',''),
(171,'attenzione','Concentrazione dei sensi e della mente su un oggetto.',''),
(172,'cassetto','Elemento formato da un piano di fondo e da quattro bordi.',''),
(173,'rappresentare','Riprodurre, raffigurare la realtà con figure disegnate.',''),
(174,'omaggiare',"L'insieme delle operazioni di nautica.",''),
(175,'abbonato','Contrarre un abbonamento a un servizio.',''),
(176,'abbinare','Riunire a coppie più persone o cose affini.',''),
(177,'onorare','Trattare qualcuno con onore e stima.',''),
(178,'pubblico','Che riguarda, interessa tutti i cittadini.',''),
(179,'carte','Fogli di carta o plastificato usate per giocare.',''),
(180,'fretta','Necessità di fare presto.',''),
(181,'ordinare','Disporre qualcosa o qualcuno in ordine.',''),
(182,'addormentare','Far prendere sonno a qualcuno.',''),
(183,'imparare',"Acquisire conoscenze o capacità con lo studio o l'esercizio.",''),
(184,'ostile','Che ha o denota avversione.',''),
(185,'vendere','Cedere ad altri la proprietà di un bene.',''),
(186,'presente','Che prende parte a qualcosa.',''),
(187,'peggio','In modo qualitativamente più scadente.',''),
(188,'assicurare','Rendere sicuro qualcosa.',''),
(189,'pancia','Addome, ventre umano o animale.',''),
(190,'finire',"Terminare, concludere un'attività.",''),
(191,'pensare','Volgere il pensiero a qualcuno o a qualcosa.',''),
(192,'parete',' Struttura verticale che delimita spazi contigui.',''),
(193,'girare','Circondare qualcosa, correre intorno a qualcosa.',''),
(194,'accessori','Che si accompagna a una cosa principale.',''),
(195,'colla','Qualunque sostanza tenace e viscosa usata per attaccare.',''),
(196,'passante','Che passa, oltrepassa, cammina.',''),
(197,'amico','Che dimostra o denota solidarietà.',''),
(198,'forte','Dotato di energia muscolare.',''),
(199,'tempo','Dimensione nella quale si concepisce e si misura il trascorrere degli eventi.',''),
(200,'abilitato','Autorizzare, rendere abile qualcuno a una professione.',''),
(201,'medico','Chi esercita la professione medica.',''),
(202,'acconto','Parte di un pagamento che viene anticipata prima della conclusione di un lavoro.',''),
(203,'divenire','Assumere una qualità, una condizione o un ruolo diversi dai precedenti.',''),
(204,'fiducia','Sensazione di sicurezza basata sulla speranza o sulla stima riposta in qualcuno o qualcosa.',''),
(205,'ospizio','Luogo in cui sono ricoverate persone anziane bisognose di assistenza.',''),
(206,'ripieno','Completamente pieno, ricolmo.',''),
(207,'merito','Diritto alla stima, alla riconoscenza.',''),
(208,'sorprendere',"Cogliere qualcuno all'improvviso",''),
(209,'articolo','Particella grammaticale che si aggiunge al nome.',''),
(210,'abbandonare','Lasciare definitivamente luoghi o persone.',''),
(211,'morale',"L'insieme dei principi generali che guidano il nostro comportamento.",''),
(212,'grave','Dotato di peso.',''),
(213,'abbondante','Che è in grande quantità.',''),
(214,'intenzione',"Proposito di attuare un'azione",''),
(215,'costruire','Ideare ed eseguire, fabbricare un manufatto.',''),
(216,'percorso','Spostamento lungo un itinerario a piedi.',''),
(217,'bravo','Contrario del selvaggio e del malvagio.',''),
(218,'cielo',"Spazio siderale percepibile, di colore variabile a causa dell'atmosfera terrestre.",''),
(219,'compagno','Chi fa qualcosa insieme con altri.',''),
(220,'trascinare','Tirare qualcosa facendolo strisciare per terra.',''),
(221,'produzione','Operazione, processo grazie ai quali qualcosa prende forma.',''),
(222,'vasto','Che è molto ampio, esteso.',''),
(223,'durare','Protrarsi da, per o fino a un certo tempo',''),
(224,'marito','Uomo sposato.',''),
(225,'comodino','Piccolo cassettone, munito di sportello e di cassetto.',''),
(226,'comprendere','Contenere in sé, racchiudere, includere qualcosa.',''),
(227,'leggero','Che pesa poco.',''),
(228,'silenzio','Assenza di ogni forma di rumore.',''),
(229,'strano','Di persona, che pensa e agisce in maniera fuori del comune, anomala.',''),
(230,'furioso','Che si abbandona ad atti violenti.',''),
(231,'agente',"Chi svolge un'attività per conto di altri.",''),
(232,'occasione','Caso che consente o favorisce qualcosa.',''),
(233,'gatto','Piccolo felino, dal corpo agile e flessuoso.',''),
(234,'rispondere','Replicare a qualcosa o a qualcuno.',''),
(235,'bicchiere','Piccolo recipiente di varie fogge usato per bere.',''),
(236,'accadere','Succedere, capitare casualmente a qualcuno.',''),
(237,'sapere','Essere o venire a conoscenza di qualcosa.',''),
(238,'spina','Escrescenza rigida e acuminata.',''),
(239,'pentola','Recipiente da cucina, perlopiù in metallo.',''),
(240,'immaginare','Rappresentare, raffigurare immagini nella mente.',''),
(241,'piacere','Sensazione di appagamento fisico.',''),
(242,'natura',"L'insieme di tutte le cose esistenti considerato nella sua forma complessiva.",''),
(243,'prendere','Afferrare, stringere qualcuno o qualcosa.',''),
(244,'spettacolo','Rappresentazione scenica o cinematografica.',''),
(245,'attrezzo',"Qualsiasi cosa preparata ad arte che serve per compiere convenientemente un'attività.",''),
(246,'materasso','Ampio contenitore squadrato di forma rettangolare.',''),
(247,'imbuto','Arnese di forma conica terminante con un cannello.',''),
(248,'accendere','Fare ardere qualcosa.',''),
(249,'orrendo','Che fa orrore, che suscita raccapriccio per le sue caratteristiche crudeli.',''),
(250,'chiedere','Domandare qualcosa o qualcuno per ottenerlo.',''),
(251,'soffrire','Detto di persona, provare dolore fisico o morale.',''),
(252,'muovere',"Iniziare un'azione contro qualcuno.",''),
(253,'accogliere','Ricevere qualcuno.',''),
(254,'abilitata','Autorizzare, rendere abile qualcuno.',''),
(255,'ortaggio','Persona che forze militari nemiche o gruppi criminali.',''),
(256,'bestia',"L'animale in genere, con esclusione dell'uomo.",''),
(257,'svegliare','Destare qualcuno, interromperne il sonno.',''),
(258,'piano',"Giovane che ostenta un'eleganza ricercata ma di cattivo gusto",''),
(259,'immagine',"Forma con la quale una cosa appare a chi la guarda.",''),
(260,'torta','Vivanda dolce caratterizzata dalla forma schiacciata e generalmente tonda.',''),
(261,'figlia','Prole di sesso femminile.',''),
(262,'coprire',"Mettere una cosa sopra un'altra per chiuderla.",''),
(263,'provare','Sottoporre qualcosa a prova.',''),
(264,'stanco','Privo di forze, di energia, a causa di un affaticamento fisico o mentale.',''),
(265,'nazionale','Della nazione, proprio di una nazione.',''),
(266,'cornetto','Amuleto a forma di piccolo corno.',''),
(267,'dolore','Sensazione fisica che dà pena, che provoca malessere.',''),
(268,'partenza','Fase iniziale dello spostamento da un luogo per un altro.',''),
(269,'inutile','Che non serve perché superfluo, inefficace o inutilizzabile.',''),
(270,'ritornare','Ricominciare a fare qualcosa.',''),
(271,'nebbia','Fenomeno meteorologico per il quale una nube si forma a contatto con il suolo.',''),
(272,'netto','Completamente mondo da ogni sporcizia.',''),
(273,'neutro','Che tra due cose opposte o contrastanti.',''),
(274,'vento',"Movimento di una massa d'aria.",''),
(275,'ferro','Elemento chimico.',''),
(276,'denaro','Nome collettivo per designare soldi, quattrini.',''),
(277,'pubblico','Che riguarda, interessa tutti i cittadini.',''),
(278,'candela','Cilindro di cera.',''),
(279,'accademia','Associazione pubblica o privata regolata da statuti per sviluppare gli studi.',''),
(280,'oscuro','Senza luce o scarsamente illuminato',''),
(281,'noleggio','Contratto con cui si cede in uso provvisorio un mezzo di trasporto.',''),
(282,'intero','A cui nulla è stato sottratto.',''),
(283,'orario','Il tempo, computato in ore.',''),
(284,'maggiore','Più grande, superiore.',''),
(285,'sogno','Fenomeno psichico legato al sonno.',''),
(286,'tagliacarte','Arnese da scrivania a forma di coltello usato per tagliare fogli di carta.',''),
(287,'amore','Affetto intenso, assiduo, fortemente radicato per qualcuno.',''),
(288,'esercito','Insieme di uomini istruiti ed equipaggiati per la guerra.',''),
(289,'ricordare','Avere presente nella memoria, rammentare qualcosa o qualcuno.',''),
(290,'abito','Indumento che si porta sopra la biancheria.',''),
(291,'rosso',"Primo colore dell'arcobaleno.",''),
(292,'ragazzo',"Uomo giovane di età compresa fra l'adolescenza e la giovinezza ",''),
(293,'guanti','Accessorio che copre la mano aderendovi perfettamente.',''),
(294,'paura','Sensazione di forte preoccupazione.',''),
(295,'confronto','Esame comparato di due o più entità.',''),
(296,'mangiare','Ingerire, masticando e deglutendo, una sostanza solida.',''),
(297,'strada','Fascia di terreno spianato, perlopiù pavimentato o asfaltato.',''),
(298,'stare','Trovarsi o restare in un dato luogo.',''),
(299,'penisola','Territorio che sporge da un continente protendendosi nel mare .',''),
(300,'monte','Rilievo geomorfologico più alto della collina.',''),
(301,'sistema','Connessione di elementi.',''),
(302,'abitazione',"Luogo o costruzione dove l'uomo risiede.",''),
(303,'lampadina','Lampada elettrica di potenza relativamente limitata.',''),
(304,'medio','Normale, che si trova a metà tra due estremi.',''),
(305,'palpare','Toccare insistentemente con la mano aperta.',''),
(306,'bambino',"L'individuo umano nell'età compresa tra la nascita e l'inizio della fanciullezza.",''),
(307,'ghiaccio',"Stato solido dell'acqua.",''),
(308,'nazionale',"
Pertinente all'ambito della nazione.",''),
(309,'riuscire','Di un fatto, concludersi in modo conforme.',''),
(310,'condizione','Costituisce il presupposto necessario perché qualcosa debba aver luogo.',''),
(311,'ottagono','Poligono piano avente otto lati.',''),
(312,'venire','Arrivare da un luogo, provenire.',''),
(313,'accesso','
La possibilità o il diritto di accedere a un luogo o a una professione.',''),
(314,'abbassato','Spostato verso il basso.',''),
(315,'cestino','Recipiente per rifiuti.',''),
(316,'ridurre','Rendere inferiore di numero, diminuire.',''),
(317,'avvicinare','Mettere più vicino, accostare.',''),
(318,'poesia',"L'espressione metaforica di contenuti umani",''),
(319,'guardare','Soffermare, volgere lo sguardo su qualcosa o su qualcuno.',''),
(320,'restare',"Fermarsi in un luogo, anche per svolgere un'attività
 ",''),
(321,'materia','Entità provvista di una propria consistenza fisica, dotata di peso.',''),
(322,'amaro',"Uno dei quattro sapori fondamentali.",''),
(323,'pericoloso','Che comporta rischi e pericoli.',''),
(324,'ostaggio','Persona che si offre alla parte nemica o è da questa catturata.',''),
(325,'sembrare',"Avere l'aspetto di qualcos'altro, assomigliare.",''),
(326,'ventola','Arnese per ravvivare il fuoco.',''),
(327,'lettera','Comunicazione scritta da inviare a qualcuno.',''),
(328,'aprire','Rendere accessibile.',''),
(329,'energia','Capacità che un corpo ha di compiere lavoro.',''),
(330,'pantofola','Calzatura morbida e leggera, che copre interamente il piede.',''),
(331,'cittadino','Proprio della città e della vita che vi si svolge.',''),
(332,'buttare','Spingere, far cadere.',''),
(333,'speranza','Attesa fiduciosa, più o meno giustificata.',''),
(334,'contento','Visibilmente lieto, allegro.',''),
(335,'presentare','Mostrare qualcosa ad altri in modo che venga esaminato.',''),
(336,'accendino','Accendisigari tascabile.',''),
(337,'foglia','Organo ad accrescimento limitato delle piante.',''),
(338,'filetto','Sottile ornamento filiforme.',''),
(339,'massimo','Il punto più alto, la quantità più grande possibile.',''),
(340,'piccante','Di sapore acuto e pungente.',''),
(341,'evitare','Fare a meno di una cosa ritenuta dannosa o fastidiosa.',''),
(342,'cucina','Ambiente riservato e attrezzato per la preparazione e la cottura dei cibi.',''),
(343,'occupare','Prendere possesso di un luogo imponendovi la propria presenza legittimamente o meno.',''),
(344,'uguale','Che si trova in condizioni di parità rispetto a un criterio comparativo.',''),
(345,'telefono','Dispositivo che permette la trasmissione a distanza di voci e suoni.',''),
(346,'palestra','Locale attrezzato per lo svolgimento di esercizi atletici o ginnici.',''),
(347,'nemico','Chi si atteggia o si comporta in modo da provocare il danno e la sconfitta altrui.',''),
(348,'orologio','Strumento atto a misurare intervalli di tempo, in ore, minuti e secondi.',''),
(349,'moglie','Il coniuge di sesso femminile.',''),
(350,'futuro','Relativo al corso del tempo successivo al presente.',''),
(351,'adesione','Contatto stabile ottenuto naturalmente o artificialmente; aderenza.',''),
(352,'unire','Mettere insieme più elementi in modo che costituiscano o appaiano un tutto unico.',''),
(353,'colpo','Percossa, urto tra due o più corpi.',''),
(354,'famoso',"Universalmente noto per l'eccezionalità degli aspetti positivi o negativi che presenta.",''),
(355,'domanda',"L'insieme delle parole con cui si esprime la richiesta di qualcosa.",''),
(356,'parente','La persona in quanto termine di un rapporto di parentela.',''),
(357,'porta','Facchino, portatore.',''),
(358,'scorrere','Avanzare, spostarsi lungo un condotto, una sede o una guida.',''),
(359,'riempire',"Rendere pieno ciò che è vuoto o libero, colmare.",''),
(360,'sperare','Confidare nella possibilità che si realizzi qualcosa ritenuto positivo.',''),
(361,'otturare','Chiudere completamente, ostruire, tappare.',''),
(362,'inverno',"La quarta stagione dell'anno.",''),
(363,'brutto','Che riesce sgradevole o suscita contrarietà o repulsione.',''),
(364,'particella','Frazione o entità concreta, minuta o minima.',''),
(365,'pacifico','Amante della tranquillità o anche della placidità.',''),
(366,'grosso','Difficile o faticoso ad affrontarsi o a sopportarsi.',''),
(367,'giorno','Tempo impiegato dalla Terra per compiere una rotazione completa attorno al proprio asse.',''),
(368,'nodulo','Piccola formazione tondeggiante cutanea o dei tessuti più profondi.',''),
(369,'lasagna','Pasta alimentare tagliata a larghe strisce.',''),
(370,'cuscino','Involucro di tessuto, riempito di lana.',''),
(371,'partire','Allontanarsi da un luogo per arrivare a un altro.',''),
(372,'palco','Ripiano costituito da una serie di assi e travi fra loro connesse.',''),
(373,'desiderare','Avvertire la mancanza, sentire il bisogno di qualcosa.',''),
(374,'dimenticare','Cancellare dalla memoria, non ricordare più, scordare.',''),
(375,'fermare','Bloccare, arrestare un oggetto, un animale o un veicolo in movimento.',''),
(376,'trattare','Prendere in esame un argomento per scritto o a voce, affrontare.',''),
(377,'madre','La donna che ha concepito e partorito.',''),
(378,'neutrale','Estraneo a un conflitto internazionale.',''),
(379,'dottore','Chi ha compiuto gli studi universitari e discussa una tesi.',''),
(380,'lavapiatti','Addetto a lavare le stoviglie in alberghi.',''),
(381,'pendolo','Sistema fisico costituito da un filo inestensibile e da una massa.',''),
(382,'crescere','Aumentare progressivamente di proporzioni.',''),
(383,'poeta','Autore di componimenti poetici.',''),
(384,'carne','La parte muscolare e dei tessuti molli del corpo umano.',''),
(385,'sognare','Vedere, immaginare in sogno.',''),
(386,'agitato','Inquieto, turbato, eccitato.',''),
(387,'gioco','Qualsiasi esercizio, singolo o collettivo, cui si dedichino bambini o adulti per passatempo.',''),
(388,'discorso','Manifestazione del proprio pensiero.',''),
(389,'tazza',"Piccolo recipiente per l'assunzione di liquidi.",''),
(390,'differenza','Condizione per cui una o più cose si trovano in totale o parziale diversità.',''),
(391,'giardino','Porzione di terreno coltivata a piante ornamentali.',''),
(392,'piangere','Lacrimare per il dolore, per la commozione.',''),
(393,'abate','Il superiore di un monastero autonomo eletto dagli stessi monaci.',''),
(394,'bagno',"Immersione prolungata nell'acqua o in altro liquido.",''),
(395,'circuito','Tracciato, percorso.',''),
(396,'notizia',"Oggetto di comunicazione o diffusione, ritenuto importante per l'interpretazione di fatti.",''),
(397,'penitenziario','Stabilimento carcerario.',''),
(398,'piede',"Parte terminale degli arti inferiori dell'uomo.",''),
(399,'saltare','Staccarsi da terra in una successione di movimenti comprendente lo slancio.',''),
(400,'abitare','Risiedere in un luogo.',''),
(401,'sedia','',''),
(402,'fuoco','',''),
(403,'elica','',''),
(404,'pensiero','',''),
(405,'popolo','',''),
(406,'acqua','',''),
(407,'determinare','',''),
(408,'fiume','',''),
(409,'vicino','',''),
(410,'interessare','',''),
(411,'escludere','',''),
(412,'conto','',''),
(413,'povero','',''),
(414,'stella','',''),
(415,'epoca','',''),
(416,'volto','',''),
(417,'dimostrare','',''),
(418,'giornale','',''),
(419,'veloce','',''),
(420,'ospite','',''),
(421,'papera','',''),
(422,'figura','',''),
(423,'resistere','',''),
(424,'prodotto','',''),
(425,'bianco','',''),
(426,'pesante','',''),
(427,'scambiare','',''),
(428,'rapido','',''),
(429,'nevicare','',''),
(430,'acquario','',''),
(431,'credere','',''),
(432,'acquedotti','',''),
(433,'cerca','',''),
(434,'reale','',''),
(435,'legge','',''),
(436,'diverso','',''),
(437,'fiore','',''),
(438,'semplice','',''),
(439,'papiro','',''),
(440,'frutto','',''),
(441,'libreria','',''),
(442,'abbastanza','',''),
(443,'accanto','',''),
(444,'storia','',''),
(445,'bisogno','',''),
(446,'resto','',''),
(447,'orchestra','',''),
(448,'folla','',''),
(449,'pazzo','',''),
(450,'adesivo','',''),
(451,'studio','',''),
(452,'mandare','',''),
(453,'lungo','',''),
(454,'festa','',''),
(455,'cercare','',''),
(456,'accumulare','',''),
(457,'ninfa','',''),
(458,'addizione','',''),
(459,'abitudine','',''),
(460,'bruciare','',''),
(461,'pedale','',''),
(462,'andare','',''),
(463,'suonare','',''),
(464,'pomeriggio','',''),
(465,'pregare','',''),
(466,'letto','',''),
(467,'scopo','',''),
(468,'abbiamo','',''),
(469,'onesto','',''),
(470,'dente','',''),
(471,'discutere','',''),
(472,'acciaio','',''),
(473,'forbici','',''),
(474,'imbuto','',''),
(475,'abbreviare','',''),
(476,'fiammifero','',''),
(477,'studiare','',''),
(478,'accessorio','',''),
(479,'partita','',''),
(480,'vivace','',''),
(481,'volare','',''),
(482,'prevedere','',''),
(483,'grado','',''),
(484,'mattarello','',''),
(485,'vista','',''),
(486,'sapone','',''),
(487,'segnare','',''),
(488,'paese','',''),
(489,'paletto','',''),
(490,'economico','',''),
(491,'signora','',''),
(492,'padrino','',''),
(493,'scomparire','',''),
(494,'godere','',''),
(495,'iniziare','',''),
(496,'risoluto','',''),
(497,'accumulo','',''),
(498,'abbinata','',''),
(499,'fornire','',''),
(500,'superare','',''),
(501,'fornello','',''),
(502,'pareggiare','',''),
(503,'accedere','',''),
(504,'abbandono','',''),
(505,'ordine','',''),
(506,'viaggio','',''),
(507,'nomignolo','',''),
(508,'capire','',''),
(509,'passo','',''),
(510,'amare','',''),
(511,'parolaccia','',''),
(512,'risoluzione','',''),
(513,'dolce','',''),
(514,'cavallo','',''),
(515,'accettabile','',''),
(516,'spugna','',''),
(517,'mettere','',''),
(518,'inferno','',''),
(519,'acquisto','',''),
(520,'possedere','',''),
(521,'numero','',''),
(522,'giudizio','',''),
(523,'piombo','',''),
(524,'chiaro','',''),
(525,'treno','',''),
(526,'paraluce','',''),
(527,'consiglio','',''),
(528,'largo','',''),
(529,'insalata','',''),
(530,'braccio','',''),
(531,'confessione','',''),
(532,'lavatrice','',''),
(533,'ponte','',''),
(534,'acceso','',''),
(535,'lavoro','',''),
(536,'dormire','',''),
(537,'cominciare','',''),
(538,'abbattere','',''),
(539,'richiedere','',''),
(540,'professore','',''),
(541,'fronte','',''),
(542,'sbagliare','',''),
(543,'mondo','',''),
(544,'polvere','',''),
(545,'crisi','',''),
(546,'calcio','',''),
(547,'accensione','',''),
(548,'pantera','',''),
(549,'fermata','',''),
(550,'bello','',''),
(551,'celebrare','',''),
(552,'peloso','',''),
(553,'cucina','',''),
(554,'eccellere','',''),
(555,'ridere','',''),
(556,'bosco','',''),
(557,'rapporto','',''),
(558,'proposta','',''),
(559,'albergo','',''),
(560,'parata','',''),
(561,'strumento','',''),
(562,'piccolo','',''),
(563,'partorire','',''),
(564,'meritare','',''),
(565,'limite','',''),
(566,'canzone','',''),
(567,'assoluto','',''),
(568,'abbonare','',''),
(569,'accompagnare','',''),
(570,'tavolo','',''),
(571,'pedone','',''),
(572,'giornata','',''),
(573,'accodare','',''),
(574,'automobile','',''),
(575,'linea','',''),
(576,'lingua','',''),
(577,'lampadario','',''),
(578,'aspetto','',''),
(579,'vestito','',''),
(580,'sorridere','',''),
(581,'scarso','',''),
(582,'spiegare','',''),
(583,'accusare','',''),
(584,'sedere','',''),
(585,'lanciare','',''),
(586,'valigia','',''),
(587,'accettare','',''),
(588,'trovare','',''),
(589,'paragrafo','',''),
(590,'centrale','',''),
(591,'olimpiade','',''),
(592,'politico','',''),
(593,'collina','',''),
(594,'parodia','',''),
(595,'animo','',''),
(596,'allontanare','',''),
(597,'raccontare','',''),
(598,'famiglia','',''),
(599,'patatine','',''),
(600,'corsa','',''),
(601,'distinguere','',''),
(602,'motivo','',''),
(603,'breve','',''),
(604,'adorare','',''),
(605,'impossibile','',''),
(606,'guida','',''),
(607,'gente','',''),
(608,'linguaggio','',''),
(609,'navigare','',''),
(610,'pronto','',''),
(611,'chiave','',''),
(612,'ostacolare','',''),
(613,'marcia','',''),
(614,'gridare','',''),
(615,'percorrere','',''),
(616,'spazio','',''),
(617,'spegnere','',''),
(618,'sentire','',''),
(619,'opera','',''),
(620,'ottenere','',''),
(621,'pacchia','',''),
(622,'addossare','',''),
(623,'accecata','',''),
(624,'azione','',''),
(625,'cameriere','',''),
(626,'significare','',''),
(627,'morte','',''),
(628,'particolare','',''),
(629,'guerra','',''),
(630,'abituare','',''),
(631,'attimo','',''),
(632,'partecipare','',''),
(633,'orecchietta','',''),
(634,'mostrare','',''),
(635,'preferire','',''),
(636,'pagare','',''),
(637,'parcheggiare','',''),
(638,'accoppiare','',''),
(639,'cuore','',''),
(640,'appartenere','',''),
(641,'pagina','',''),
(642,'entrare','',''),
(643,'concedere','',''),
(644,'signore','',''),
(645,'abbassare','',''),
(646,'diritto','',''),
(647,'pianura','',''),
(648,'orecchio','',''),
(649,'vivere','',''),
(650,'territorio','',''),
(651,'criticare','',''),
(652,'divertire','',''),
(653,'potenza','',''),
(654,'opzione','',''),
(655,'moderato','',''),
(656,'tostapane','',''),
(657,'scatola','',''),
(658,'diretto','',''),
(659,'risposta','',''),
(660,'addestrare','',''),
(661,'tirare','',''),
(662,'parrucchiere','',''),
(663,'paesano','',''),
(664,'offerta','',''),
(665,'foglio','',''),
(666,'incontrare','',''),
(667,'abbraccio','',''),
(668,'offrire','',''),
(669,'bellezza','',''),
(670,'pensione','',''),
(671,'fazzoletto','',''),
(672,'concerto','',''),
(673,'paragonare','',''),
(674,'accomodare','',''),
(675,'nessuno','',''),
(676,'freddo','',''),
(677,'specie','',''),
(678,'scrivere','',''),
(679,'umano','',''),
(680,'paziente','',''),
(681,'progetto','',''),
(682,'ossigeno','',''),
(683,'tenda','',''),
(684,'popolazione','',''),
(685,'ammazzare','',''),
(686,'rispetto','',''),
(687,'destro','',''),
(688,'importanza','',''),
(689,'accorciare','',''),
(690,'campana','',''),
(691,'bastare','',''),
(692,'cantare','',''),
(693,'terreno','',''),
(694,'barattolo','',''),
(695,'creare','',''),
(696,'ostrica','',''),
(697,'lettera','',''),
(698,'accettare','',''),
(699,'parroco','',''),
(700,'levare','',''),
(701,'succedere','',''),
(702,'pianta','',''),
(703,'capitare','',''),
(704,'portachiave','',''),
(705,'attore','',''),
(706,'leggere','',''),
(707,'spesa','',''),
(708,'sforzo','',''),
(709,'sposare','',''),
(710,'comprare','',''),
(711,'bravura','',''),
(712,'alzare','',''),
(713,'descrivere','',''),
(714,'confessare','',''),
(715,'seguire','',''),
(716,'divano','',''),
(717,'procedere','',''),
(718,'coraggio','',''),
(719,'adorabile','',''),
(720,'originale','',''),
(721,'esistere','',''),
(722,'peggiorare','',''),
(723,'facile','',''),
(724,'penna','',''),
(725,'grazioso','',''),
(726,'fuggire','',''),
(727,'ultimo','',''),
(728,'zuppa','',''),
(729,'morire','',''),
(730,'oroscopo','',''),
(731,'segnale','',''),
(732,'salire','',''),
(733,'albero','',''),
(734,'negozio','',''),
(735,'pancetta','',''),
(736,'tentare','',''),
(737,'cenare','',''),
(738,'vecchio','',''),
(739,'battaglia','',''),
(740,'pecora','',''),
(741,'dipendere','',''),
(742,'accendere','',''),
(743,'pensionato','',''),
(744,'profondo','',''),
(745,'svolgere','',''),
(746,'baciare','',''),
(747,'uscire','',''),
(748,'neurone','',''),
(749,'palio','',''),
(750,'narrare','',''),
(751,'italiano','',''),
(752,'abbinato','',''),
(753,'salvare','',''),
(754,'aderente','',''),
(755,'pesare','',''),
(756,'acquedotto','',''),
(757,'paralume','',''),
(758,'nomade','',''),
(759,'pareggio','',''),
(760,'ragazza','',''),
(761,'colore','',''),
(762,'normativa','',''),
(763,'caldo','',''),
(764,'affettuoso','',''),
(765,'accessibile','',''),
(766,'ritorno','',''),
(767,'libro','',''),
(768,'cattivo','',''),
(769,'triste','',''),
(770,'periodo','',''),
(771,'tagliare','',''),
(772,'informazione','',''),
(773,'liberare','',''),
(774,'risolvere','',''),
(775,'mappa','',''),
(776,'corrente','',''),
(777,'contatto','',''),
(778,'formaggio','',''),
(779,'insegnare','',''),
(780,'parentela','',''),
(781,'vedere','','');