INSERT INTO hardwords(ID, Word, Meaning, Category) VALUES
(1,'aborto','Interruzione della gravidanza.',''),
(2,'abdico','Rinunciare formalmente ad una carica.',''),
(3,'provincia','Circoscrizione territoriale amministrativa.',''),
(4,'fodero',"Contenitore di un'arma bianca.",''),
(5,'abbattere','Avvertire un senso di profondo sconforto.',''),
(6,'addolorare','Rendere molto triste e dispiaciuto.',''),
(7,'tremolio','Serie continua di rapide vibrazioni.',''),
(8,'oppioide','Composto chimico con effetti simili alla morfina.',''),
(9,'giavellotto',"Un'arma da lancio.",''),
(10,'patrigno','Il secondo marito di una donna rimasta vedova.',''),
(11,'oblio','Perdita di memoria duratura.',''),
(12,'stentato','Ottenere con sforzo e difficoltà.',''),
(13,'miracolo','Fatto dovuto a un intervento soprannaturale.',''),
(14,'appoggiare',"Mettere una cosa a ridosso di un'altra.",''),
(15,'accigliare','Aggrottare le sopracciglia per sdegno, tristezza.',''),
(16,'radiatore','Dispositivo per il riscaldamento degli ambienti',''),
(17,'pachiderma',"Ordine di mammiferi, come l'elefante.",''),
(18,'pedagogico','Concernente la pedagogia.',''),
(19,'concetto','Pensiero definito e idealmente configurato.',''),
(20,'pazzerello','Persona sventata o capricciosa.',''),
(21,'pentagramma','Piano cartesiano che ha il tempo in ascissa e la frequenza in ordinata.',''),
(22,'carreggiata','La parte della strada destinata allo scorrimento dei veicoli.',''),
(23,'stagno','Metallo di post-transizione argenteo e malleabile.',''),
(24,'innamorare','Concepire una passione amorosa per qualcuno.',''),
(25,'adiacenza','Luogo vicino o in prossimità.',''),
(26,'spinterogeno','Dispositivo per generare la scintilla.',''),
(27,'oltraggiare','Offendere in modo grave.',''),
(28,'arpeggio','Accordo musicale.',''),
(29,'olocausto','Genocidio perpetrato dalla Germania nazista.',''),
(30,'chilometro',"E' un unita di lunghezza del Sistema Internazionale.",''),
(31,'ocarina','Strumento musicale popolare a fiato.',''),
(32,'pellicano','Genere di uccelli acquatici.',''),
(33,'tappezzeria','La tecnica di arte-artigianato di rivestimento di pareti.',''),
(34,'abluzione','Lavanda sommaria del corpo.',''),
(35,'accomiata','Dare commiato, lincenziare, congedare.',''),
(36,'nichel',"Elemento chimico usato solitamente per l'acciaio.",''),
(37,'antico','Risalente a tempi remoti.',''),
(38,'paffuto','Grassoccio, detto per lo più dei bambini sani e ben nutriti.',''),
(39,'straordinario','Non ordinario, fuori dalla norma.',''),
(40,'sentimento','Momento della vita interiore, pertinente al mondo delle emozioni.',''),
(41,'nuraghe','Tipo di costruzione sarda in pietra.',''),
(42,'costruzione','Ideare ed eseguire, fabbricare un manufatto.',''),
(43,'necropoli','Agglomerato di tombe.',''),
(44,'acustico',"Serve a migliorare o correggere le facoltà dell'udito.",''),
(45,'additare','Mostrare con il dito.',''),
(46,'clausola','Condizione di un contratto.',''),
(47,'divaricatore','Utilizzato nelle operazioni chirurgiche per allargare i lembi di una ferita.',''),
(48,'abiurato','Rigetto di una precedente ideologia.',''),
(49,'capriccio','Voglia improvvisa e stravagante.',''),
(50,'trinciante','Coltello per tagliare grossi pezzi di carne.',''),
(51,'originario','Che proviene da un luogo determinato.',''),
(52,'occhiaia','Cavità oculare del cranio.',''),
(53,'disinfettante','Misura atta a ridurre la maggior quantità di microrganismi.',''),
(54,'paradisiaco','Luogo ameno e incantevole.',''),
(55,'chitarra','Strumento musicale cordofono.',''),
(56,'asciugamano','Panno usato per asciugarsi dopo essersi lavati.',''),
(57,'uliva',"Il frutto dell'olivo",''),
(58,'schiantare','Rompere in modo violento, istantaneo.',''),
(59,'assicurazione','Rendere sicuro qualcuno o qualcosa.',''),
(60,'ominide','Famiglia di primati.',''),
(61,'orbitare',"Descrivere un'orbita intorno a un altro corpo.",''),
(62,'patriottico',"Ispirato alla difesa o all'esaltazione della patria.",''),
(63,'nodulare','Struttura innaturale.',''),
(64,'sbandare','Deviare improvvisamente e accidentalmente dal normale assetto di marcia.',''),
(65,'difficile','Che richiede notevole sforzo, abilità, attenzione o applicazione mentale.',''),
(66,'pediluvio','Trattamento idroterapico.',''),
(67,'deragliare','Uscire dalle rotaie.',''),
(68,'parteggiare','Militare in un partito o in una fazione.',''),
(69,'avanzare','Andare avanti, procedere.',''),
(70,'depuratore',"Dispositivo che serve per eliminare impurità dall'acqua.",''),
(71,'negligente','Svogliato nei propri doveri.',''),
(72,'terme','Complesso di edifici dotato di attrezzature atte a sfruttare le acque termominerali.',''),
(73,'obiettore','Chi muove obiezioni.',''),
(74,'origliare','Stare in ascolto di nascosto.',''),
(75,'motociclo','Veicolo a due ruote spinto da un motore.',''),
(76,'acustica','Branca della fisica che studia il suono.',''),
(77,'pecoreccio','Senso di goffaggine o volarità.',''),
(78,'percezione','La percezione è il processo psichico che opera la sintesi dei dati sensoriali.',''),
(79,'ovale','Che ha forma simile a un uovo.',''),
(80,'candelabro','Oggetto con la funzione di reggere le candele.',''),
(81,'salpare',"Levare l'ancora, sciogliere gli ormeggi e partire",''),
(82,'spolverino','Arnese per spolverare, per levare la polvere.',''),
(83,'addensare','Rendere più densa una sostanza.',''),
(84,'numerologia','Disciplina che studia il significato dei numeri.',''),
(85,'sacca','Grossa borsa per trasportare effetti personali o altro.',''),
(86,'ossario','Nei cimiteri, edificio in cui sono raccolte le ossa.',''),
(87,'abbagliante','Di luminosità intensa e brillante.',''),
(88,'obiettare','Contestare a quanto detto o proposto.',''),
(89,'accasciare','Cadere giù, abbattere.',''),
(90,'svoltare','Curvare, cambiare direzione.',''),
(91,'obsoleto','Antiquato, sorpassato.',''),
(92,'accigliato','Con le sopracciglia aggrottate.',''),
(93,'pergolato','Impalcatura di sostegno per piante rampicanti e viti.',''),
(94,'ammuffire','Guastarsi per la muffa.',''),
(95,'ostrogoto','Rozzo, incivile e incomprensibile.',''),
(96,'davanzale','Lastra o tavola che copre il parapetto delle finestre.',''),
(97,'biforcazione','Divisione in due parti di qualcosa.',''),
(98,'abbreviato','Rendere qualcosa più breve o più corto.',''),
(99,'eccesso','Quantità eccessiva di qualcosa.',''),
(100,'sgombro','Libero da ingombri, da ostacoli.',''),
(101,'funzione','Particolare attività o compito svolti in un dato ambito.',''),
(102,'penicellina','Antibiotico beta-lattamici.',''),
(103,'onirologia','Lo studio dei sogni.',''),
(104,'labbro',"Ciascuna delle due pieghe cutanee che delimitano l'apertura della bocca.",''),
(105,'stantio',"Privo di attualità o d'interesse.",''),
(106,'slargo','Punto in cui una strada si allarga.',''),
(107,'bisognare','Con soggetto posposto, essere necessario a qualcuno.',''),
(108,'accasare','Far sposare qualcuno.',''),
(109,'oculare',"Relativo all'occhio.",''),
(110,'cortile','Area libera, scoperta.',''),
(111,'peccaminoso','Comportamento vizioso e colpevole.',''),
(112,'accasata','Far sposare qualcuno.',''),
(113,'sgabello','Sedile per una sola persona.',''),
(114,'omettere','Tralasciare qualcosa intenzionalmente.',''),
(115,'foratura','Esecuzione di uno o più fori.',''),
(116,'riguardare','Guardare di nuovo qualcosa o qualcuno.',''),
(117,'ingorgo','Rallentamento nel deflusso di un liquido.',''),
(118,'candeliere','Sostegno per una sola candela.',''),
(119,'parabrezza','Elemento anteriore dei veicoli.',''),
(120,'strapazzare','Trattare in malo modo.',''),
(121,'opinione','Idea, giudizio individuale, punto di vista soggettivo.',''),
(122,'abiurata','Rigetto di una precedente ideologia.',''),
(123,'guardia','Mansione di chi veglia su cose e persone.',''),
(124,'adulazione','Atteggiamento di chi asseconda, lusinga o corteggia.',''),
(125,'ornitorinco','Mammifero oviparo della famiglia dei Monotremi.',''),
(126,'orefice','Chi vende oggetti di oreficeria.',''),
(127,'omologare','Approvare un oggetto ritenuto a norma di legge.',''),
(128,'indaco','Colorante di orgine vegetale.',''),
(129,'origami','Ottenere, piegando carta, figure o oggetti.',''),
(130,'percussione','Strumento musicale che suona quando percosso.',''),
(131,'imbarcare',"Far salire qualcuno o qualcosa su un'imbarcazione o un aereo.",''),
(132,'parafrasi','Consiste in una “traduzione” di un testo poetico.',''),
(133,'accogliere','Ricevere qualcuno o qualcosa.',''),
(134,'abbondo','Essere presente in grande numero o quantità.',''),
(135,'qualsiasi','Tutti i possibili, tutte le possibili.',''),
(136,'patriarcale','Relativo al patriarca, come capo famiglia.',''),
(137,'rimettere','Mettere di nuovo qualcosa in un posto.',''),
(138,'candeggina','Soluzione di ipoclorito di sodio per uso domestico.',''),
(139,'omeopatia','Pratica di pseudo-medicina.',''),
(140,'estendere','Allargarsi territorialmente.',''),
(141,'abbietto','Ripugnante, spregevole.',''),
(142,'pagliaio','Caratteristico mucchio di paglia.',''),
(143,'omonimo','Che ha lo stesso nome o titolo.',''),
(144,'rondella','Dischetto forato che si inserisce sotto il dado di un bullone.',''),
(145,'provvedere','Curarsi, occuparsi di qualcuno.',''),
(146,'pioli','Paletto di legno.',''),
(147,'nicchia','Cavità ottenuta da un muro.',''),
(148,'finestra',"Apertura di forma regolare per consentire l'ingresso della luce.",''),
(149,'maniglia','Sporgenza di varia forma applicata a porte.',''),
(150,'traghetto',"Trasporto, passaggio di persone o cose da una sponda all'altra",''),
(151,'accasato','Far sposare qualcuno.',''),
(152,'acciaieria',"Impianto industriale dove si produce e si lavora l'acciaio.",''),
(153,'onirico','Il sogno dal punto di vista psicanalitico.',''),
(154,'osmosi','Diffusione tra due liquidi miscibili.',''),
(155,'pavoneggiare','Compiacersi eccessivamente di se stesso.',''),
(156,'abbeverato','Dare da bere al bestiame.',''),
(157,'ortopedico','Medico specializzato in ortopedia.',''),
(158,'olivastro','Colore tendente al verde come le olive.',''),
(159,'ordinario','Che è nei limiti della norma e della regolarità.',''),
(160,'nutriente','Ciò che nutre aumentando la sostanza del corpo di animale o vegetale.',''),
(161,'obiettivo','Esente da pregiudizi, passioni, interessi soggettivi.',''),
(162,'abbuono','Riduzione del prezzo di una merce.',''),
(163,'mattatoio','Edificio per la macellazione animale.',''),
(164,'ovattare','Attenuare, attutire.',''),
(165,'medaglione','Ciondolo di metallo prezioso da portare al collo.',''),
(166,'pediatra','Branca della medicina che si occupa dello sviluppo psicofisico dei bambini.',''),
(167,'omerico','Poemi di Omero.',''),
(168,'stabilire','Adottare una decisione stabile e vincolante.',''),
(169,'raccordo','Collegamento fra due cose.',''),
(170,'nauseabondo','Tale da provocare la nausea.',''),
(171,'bruscamente','In maniera improvvisa, brusca.',''),
(172,'abrogato','Sopprimere una legge.',''),
(173,'proporre','Presentare, sottoporre qualcosa o qualcuno, alla sua attenzione.',''),
(174,'obbrobio','Causa di disonore, di vergogna.',''),
(175,'omertoso','Imposto da omertà.',''),
(176,'ordito',"L'insieme di fili che formano il tessuto.",''),
(177,'giungere','Arrivare, pervenire in un luogo.',''),
(178,'cruscotto',"parete anteriore dell'abitacolo posizionata al disotto del parabrezza di un autoveicolo.",''),
(179,'colossale','Di dimensioni molto grandi.',''),
(180,'pelandrone','Scansafatiche, fannullone.',''),
(181,'spremitore','Qualcosa o qualcuno che spreme.',''),
(182,'accomiato','Dare commiato, lincenziare, congedare.',''),
(183,'elevare','Rendere qualcosa più alto.',''),
(184,'tangenziale','Utilizzato per descrivere una strada a scorrimento veloce.',''),
(185,'ardesia','Varietà di argilloscisto.',''),
(186,'obbiettare','Chi muove obiezioni.',''),
(187,'scippare','Derubare qualcuno per strada.',''),
(188,'accalorare','Riscaldare qualcosa.',''),
(189,'adornare','Abbellire ornando con cura.',''),
(190,'abbreviata','Rendere qualcosa più breve o più corto.',''),
(191,'abbazia','Particolare tipo di monastero.',''),
(192,'pagoda','Costruzione sacra buddista a forma di torre piramidale a più piani.',''),
(193,'trasduttore',"Dispositivo di qualsiasi genere destinato a trasmettere dell'energia",''),
(194,'psicomante','Persona dedita alla psicomanzia.',''),
(195,'burletta','Che non è serio, che costituisce una presa in giro.',''),
(196,'otaria','Leone marino sudamericano.',''),
(197,'rotaia',"Ognuna delle due guide d'acciaio che costituiscono il binario.",''),
(198,'arrugginito','Rendere rugginoso, coprire di ruggine.',''),
(199,'tagliando','Parte di foglio che si stacca da un blocchetto a matrice o da una cartella.',''),
(200,'fusibile','Dispositivo elettrico in grado di proteggere un circuito dalle sovracorrenti.',''),
(201,'pargolo','Bambino di tenera età.',''),
(202,'pedaggio',"È una tassa per l'infrastruttura viaria.",''),
(203,'mestolo','Specie di cucchiaione di legno.',''),
(204,'grazia','Dono profuso gratuitamente da Dio.',''),
(205,'abrogare','Sopprimere una legge.',''),
(206,'orrido','Ciò che desta orrore.',''),
(207,'parificazione','Operazione che rende uguali oggetti.',''),
(208,'facchino','Chi è addetto al trasporto di colli.',''),
(209,'abbagliare','Colpire qualcuno con una luce viva, offuscandogli la vista.',''),
(210,'slittare','Andare in slitta scivolando lungo un pendio.',''),
(211,'interessante','Che stimola la curiosità, il desiderio di conoscenza.',''),
(212,'livella',"Attrezzo utilizzato per stabilire l'orizzontalità di una retta.",''),
(213,'dogana','Ufficio che esercita il controllo sulle merci che passano le frontiere di uno Stato.',''),
(214,'oratorio','Edificio di aggregazione cristiana.',''),
(215,'overdose','Dose di droga pesante.',''),
(216,'contadino','Chi coltiva, lavora la terra.',''),
(217,'turbolenza','Stato di agitazione violenta.',''),
(218,'ologramma','Immagine tridimensionale di un oggetto su lastra fotografica.',''),
(219,'adirare',"Cedere all'ira.",''),
(220,'offuscare','Oscurare qualcosa, renderlo fosco.',''),
(221,'nausea',"Malessere che si accusa all'epigastrio e alla faringe caratterizzato da rigurgito.",''),
(222,'odontoiatra','Medicina che si occupa delle patologie che colpiscono denti, gengive e ossa mascellari.',''),
(223,'raffermo','Non più fresco.',''),
(224,'patibolo',"Strumento per l'esecuzione di condanne a morte.",''),
(225,'abbruno','Rendere qualcosa scuro.',''),
(226,'aracnide','Invertebrato, come il ragno e lo scorpione, con il capo unito al torace.',''),
(227,'accasciato','Cedere a terra.',''),
(228,'occlusione','Chiusura di un canale.',''),
(229,'edilizia','Tecnica, attività volta alla costruzione e alla manutenzione di edifici.',''),
(230,'penuria','Mancanza di cose indispensabili.',''),
(231,'orifizio',"Piccola apertura all'estremità di un condotto per il passaggio dei fluidi.",''),
(232,'adulare','Compiacersi troppo di sé stesso.',''),
(233,'itinerario',"Percorso di un viaggio, di un'escursione, di una gara.",''),
(234,'fanale',"Apparecchio per l'illuminazione.",''),
(235,'congresso','Incontro, riunione di rappresentanti di stati per la definizione di questioni internazionali.',''),
(236,'orazione','Discorso solenne tenuto in pubblico.',''),
(237,'ciano','Uno degli inchiostri comunemente utilizzati nella stampa.',''),
(238,'riferire',': Riportare, raccontare ad altri quanto si è venuti a conoscere.',''),
(239,'astratto',"Che non deriva dall'esperienza sensibile ma dal puro ragionamento.",''),
(240,'allentare','Rendere qualcosa meno stretto, meno teso.',''),
(241,'abiura','Rinuncia libera e perpetua.',''),
(242,'ammorbidente','Di sostanza usata nel lavaggio dei tessuti.',''),
(243,'adombrare',"Coprire d'ombra un luogo.",''),
(244,'nozionismo',"Conoscenza fondata sull'apprendimento.",''),
(245,'abiurare','Rinuncia libera e perpetua.',''),
(246,'orinare',"Eliminare l'urina dal corpo.",''),
(247,'adagiare','Sdraiarsi su qualcosa.',''),
(248,'orfanotrofio',"Istituto per l'accoglienza e l'assistenza ai bambini orfani.",''),
(249,'importare',"Introduzione nel proprio paese di merci acquistate all'estero.",''),
(250,'nicotina',"Composto organico che può essere fatale per l'uomo.",''),
(251,'cemento','Miscela di calcari e argille unita ad acqua.',''),
(252,'strofinaccio','Straccio che si usa per lavori domestici di pulizia.',''),
(253,'ordire','Disporre longitudinalmente i fili sul telaio.',''),
(254,'nettare','Secondo la mitologia classica, la bevanda degli dei.',''),
(255,'ulivastro','Di colore bruno tendente al verde come quello delle olive.',''),
(256,'nomenclatura','Denominazioni di oggetti.',''),
(257,'oscillatorio','Che si manifesta con oscillazioni, che ha andamento periodico.',''),
(258,'omeopatico',"È un sistema di medicina naturale.",''),
(259,'panzerotto','Grosso raviolo ripieno di prosciutto.',''),
(260,'orbitale','Regione dello spazio circostante un nucleo atomico.',''),
(261,'improvviso','Qualcosa di imprevisto o di improvviso, imprevisto.',''),
(262,'cordolo','Elemento di costruzione.',''),
(263,'ornare','Abbellire ornando con cura.',''),
(264,'fenomeno',"Ciò che appare all'esperienza sensibile.",''),
(265,'assumere','Prendere su di sé, accollarsi un impegno.',''),
(266,'abrogata','Annullare una norma con un atto.',''),
(267,'falsetto','Suono disconnesso, una voce, come dice il termine stesso, "falsa".',''),
(268,'comparto','Parte risultante da una suddivisione.',''),
(269,'orchessa',"Nelle fiabe, moglie dell'orco",''),
(270,'suggeritore','Chi dà suggerimenti.',''),
(271,'oncologo','Settore della medicina che si occupa della cura dei tumori.',''),
(272,'oleoso','Contenente olio.',''),
(273,'centralina','Centrale periferica di una rete elettrica o telefonica.',''),
(274,'patriarca','Titolo tra i vescovi delle Chiese che accettano la successione apostolica.',''),
(275,'abdicato','Rinunciare formalmente ad una carica.',''),
(276,'compartimento','Ciascuna delle parti risultanti dalla suddivisione di uno spazio.',''),
(277,'impianto','Allestimento di strutture, macchinari, strumentazioni.',''),
(278,'oleodotto','Mezzo per il trasporto di petrolio.',''),
(279,'palcoscenico',"Parte dell'edificio teatrale che ospita l'azione scenica.",''),
(280,'orchidea',"Fiore appartenente all'ordine delle Orchidales.",''),
(281,'patriottismo','Fervido sentimento di devozione alla patria.',''),
(282,'patta','Apertura dei pantaloni.',''),
(283,'padiglione','Piccolo edificio, spesso a una sola stanza.',''),
(284,'fiasco','Recipiente di vetro soffiato per liquidi.',''),
(285,'abdicare','Rinunciare formalmente ad una carica.',''),
(286,'patrimonio','Definito come la ricchezza, espressa in termini monetari.',''),
(287,'accorgersi','Prendere coscienza di una presenza o realtà non immediata.',''),
(288,'addentare','Afferrare qualcosa con i denti.',''),
(289,'scordatura','Accordatura diversa dal normale negli strumenti ad arco.',''),
(290,'opificio','Stabilimento industriale per produzione di prodotti.',''),
(291,'obliterare','Annullare francobolli o biglietti con un timbro una stampigliatura.',''),
(292,'occhiello','Foro variamente orlato e rinforzato.',''),
(293,'tergivetro','Dispositivo automatico di pulizia del parabrezza.',''),
(294,'ionizzazione','Processo secondo cui atomi o molecole neutre acquistano o perdono elettroni.',''),
(295,'palanca','Grossa trave di legno.',''),
(296,'parabolico','Che ha forma di parabola.',''),
(297,'nespola','Frutto di due diverse piante.',''),
(298,'pandemia','Epidemia a rapida diffusione.',''),
(299,'giovanotto','Giovane ormai vicino alla maturità.',''),
(300,'scalpello',"Utensile d'acciaio usato per incidere.",''),
(301,'partito','Organizzazione di cittadini associati che perseguono comuni finalità.',''),
(302,'manico','Parte di un oggetto che viene impugnata per utilizzarlo.',''),
(303,'abaco',"Tavoletta per calcoli in uso nell'antichità.",''),
(304,'novizia','Che si prepara a prendere i voti religiosi.',''),
(305,'lanterna','Apparecchio per illuminazione.',''),
(306,'oberato','Oppresso da debiti.',''),
(307,'nevrosi',"Disturbo dell'adattamento",''),
(308,'otite',"Infiammazione dell'orecchio medio",''),
(309,'federa','Sacchetto di tela che ricopre il cuscino.',''),
(310,'sensore',"Dispositivo in grado di rilevare dati fisici dall'ambiente circostanze.",''),
(311,'prato','Terreno agricolo inerbito per più di un anno.',''),
(312,'paraurti','Previene o limita i danni di una collisione a bassa velocità.',''),
(313,'plagio',"Attribuzione al proprio ingegno di un'opera altrui.",''),
(314,'ornamento','Abbellimento ottenuto con elementi decorativi.',''),
(315,'ossidare',"Reazione chimica che avviene quando una sostanza o un elemento si combinano con l'ossigeno.",''),
(316,'occultare','Nascondere qualcosa, sottrarlo alla vista.',''),
(317,'ornamentale','Destinato a fini di decorazione.',''),
(318,'ventosa','Materiale elastico che aderisce ad una superficie liscia.',''),
(319,'maestro','Insegnante di scuola elementare.',''),
(320,'obitorio','Stanza contenente i cadaveri.',''),
(321,'patire','Soffrire, provare qualcosa che comporti disagio.',''),
(322,'capello','Pelo della cute del capo.',''),
(323,'maniera','Modo in cui una cosa si manifesta.',''),
(324,'violino','Strumento musicale della famiglia degli archi.',''),
(325,'pensatoio','Luogo appartato in cui ci si ritira a meditare.',''),
(326,'mulattiera','Strada per il passaggio delle carovane di muli.',''),
(327,'istruttore',"Colui che fornisce le nozioni e l'addestramento.",''),
(328,'espressione','Manifestazione di pensieri.',''),
(329,'oziare','Passare il tempo senza far nulla.',''),
(330,'oligarchia','Sistema politico in cui il governo è nelle mani di pochi potenti.',''),
(331,'ninfea',"Fiore acquatico che sboccia all'alba e si chiude al tramonto.",''),
(332,'ciclomotore','Veicolo a 2 o 3 ruote.',''),
(333,'proposito','Ciò che ci si propone di fare.',''),
(334,'onomatopea',"Fenomeno quando i suoni di una parola descrivono l'oggetto.",''),
(335,'abbrunare','Rendere qualcosa scuro',''),
(336,'pressione','Forza esercitata sulla superficie di un corpo.',''),
(337,'acquaragia','Olio essenziale di trementina.',''),
(338,'condizionare',"Esercitare un'azione che limita, modifica qualcosa o qualcuno.",''),
(339,'cartongesso','Materiale usato in edilizia per isolare o separare ambienti.',''),
(340,'pagaiare','Manovrare e muovere una canoa con le pagaie.',''),
(341,'palpeggiare','Toccare qualcosa o qualcuno con la mano.',''),
(342,'regione','Ampia porzione della superficie terrestre.',''),
(343,'cinguettio','Canto di uccelli insistito e sommesso.',''),
(344,'narcotizzare','Sottoporre qualcuno ad anestesia totale.',''),
(345,'melodramma','Dramma interamente cantato con accompagnamento strumentale.',''),
(346,'paradosso','Che ha natura assurda o incredibile.',''),
(347,'parsimonia','Moderazione nello spendere.',''),
(348,'parafango','Elemento della carrozzeria, crea una connessione tra il cofano, la parte frontale e la zona delle portiere.',''),
(349,'algoritmo','Procedimento che risolve un determinato problema.',''),
(350,'abbrunato','Rendere qualcosa scuro.',''),
(351,'cuccetta','Lettini sovrapposti ad altri come nelle cabine di navi.',''),
(352,'naufragio',"Completa sommersione di un'imbarcazione",''),
(353,'fantasia','Capacità della mente di inventare situazioni che non si danno nella realtà.',''),
(354,'paradigma','Modello di riferimento, un termine di paragone.',''),
(355,'omelia','Spiegazione e commento delle Sacre Scritture durante la messa.',''),
(356,'darsena','Un bacino acqueo artificiale.',''),
(357,'abbiente','In condizioni economiche agiate.',''),
(358,'narciso','Persona innamorata di se stessa.',''),
(359,'naftalina','Idrocarburo aromatico polinucleato.',''),
(360,'acciuga','Pesce osseo marino appartenente alla famiglia Engraulidae.',''),
(361,'insipido','Sgradevolmente privo di sapore.',''),
(362,'ombelico','Ciò che rimane della recisione praticata al cordone ombelicale.',''),
(363,'cinghia','Striscia minuta di fibbia, ganci o magliette, che serve a sostenere i pantaloni.',''),
(364,'omerale','Indumento liturgico.',''),
(365,'parificare','Concedere o riconoscere una parità sul piano giuridico e amministrativo.',''),
(366,'frizione','Organo meccanico.',''),
(367,'accalorata','Infervorata, eccitata.',''),
(368,'pagliaccio','Tipo comico tradizionale del teatro e del circo, vestito in maniera goffa.',''),
(369,'ormeggiare',"Fissare un'imbarcazione a uno o a più punti fermi.",''),
(370,'adontare','Fare onta, offendere.',''),
(371,'recare','Condurre con sé un oggetto per consegnarlo a qualcuno.',''),
(372,'obbligazione','Impegno, dovere verso terzi.',''),
(373,'ombelicale',"Relativo all'ombelico.",''),
(374,'abrasione','Lesione superficiale della pelle.',''),
(375,'accalorato','Infervorato, eccitato.',''),
(376,'obbiettore','Chi rifiuta di ottemperare a obblighi imposti dal diritto.',''),
(377,'pizzicato','Tecnica usata per suonare gli strumenti ad arco.',''),
(378,'fetecchia','Cosa o persona di nessun valore.',''),
(379,'sterzare','Manovrare lo sterzo per cambiare direzione.',''),
(380,'obbiettivo',"Che si fonda sull'analisi della realtà.",''),
(381,'pazzesco','Tipico o degno di un pazzo.',''),
(382,'orzata','Utilizzato per designare genericamente molti tipi di bevande rinfrescanti.',''),
(383,'ordigno','Congegno dal meccanismo complicato.',''),
(384,'nocivo','Che provoca un danno di varia natura o entità.',''),
(385,'adulatore','Chi adula, lusinga.',''),
(386,'otorino',"Ramo della medicina riguardante malattie dell'orecchio, del naso e della gola.",''),
(387,'paganesimo','Quelle religioni viste in opposizione al cristianesimo.',''),
(388,'acquietare','Ricondurre a uno stato di quiete.',''),
(389,'ossidiana','Vetro vulcanico che ha origine dal veloce raffreddamento di lave ricche di silicio.',''),
(390,'notabile','Notevole, degno di nota.',''),
(391,'peperone',"Pianta erbacea originaria dell'America tropicale.",''),
(392,'sparecchiare',"Liberare la tavola di tutto ciò che l'ingombra.",''),
(393,'abbeverata','Dare da bere al bestiame.',''),
(394,'oltranza','Superamento del limite consentito o conveniente.',''),
(395,'palmento',"Luogo in cui avveniva la pigiatura dell'uva.",''),
(396,'natica','Ciascuna delle due masse carnose sporgenti posteriormente.',''),
(397,'coadiuvare','Aiutare qualcuno o qualcosa.','');