INSERT INTO hardwords VALUES (1,'aborto','Interruzione della gravidanza.','');
INSERT INTO hardwords VALUES (2,'abdico','Rinunciare formalmente ad una carica.','');
INSERT INTO hardwords VALUES (3,'provincia','Circoscrizione territoriale amministrativa.','');
INSERT INTO hardwords VALUES (4,'fodero',"Contenitore di un'arma bianca.",'');
INSERT INTO hardwords VALUES (5,'abbattere','Avvertire un senso di profondo sconforto.','');
INSERT INTO hardwords VALUES (6,'addolorare','Rendere molto triste e dispiaciuto.','');
INSERT INTO hardwords VALUES (7,'tremolio','Serie continua di rapide vibrazioni.','');
INSERT INTO hardwords VALUES (8,'oppioide','Composto chimico con effetti simili alla morfina.','');
INSERT INTO hardwords VALUES (9,'giavellotto',"Un'arma da lancio.",'');
INSERT INTO hardwords VALUES (10,'patrigno','Il secondo marito di una donna rimasta vedova.','');
INSERT INTO hardwords VALUES (11,'oblio','Perdita di memoria duratura.','');
INSERT INTO hardwords VALUES (12,'stentato','Ottenere con sforzo e difficoltà.','');
INSERT INTO hardwords VALUES (13,'miracolo','Fatto dovuto a un intervento soprannaturale.','');
INSERT INTO hardwords VALUES (14,'appoggiare',"Mettere una cosa a ridosso di un'altra.",'');
INSERT INTO hardwords VALUES (15,'accigliare','Aggrottare le sopracciglia per sdegno, tristezza.','');
INSERT INTO hardwords VALUES (16,'radiatore','Dispositivo per il riscaldamento degli ambienti','');
INSERT INTO hardwords VALUES (17,'pachiderma',"Ordine di mammiferi, come l'elefante.",'');
INSERT INTO hardwords VALUES (18,'pedagogico','Concernente la pedagogia.','');
INSERT INTO hardwords VALUES (19,'concetto','Pensiero definito e idealmente configurato.','');
INSERT INTO hardwords VALUES (20,'pazzerello','Persona sventata o capricciosa.','');
INSERT INTO hardwords VALUES (21,'pentagramma','Piano cartesiano che ha il tempo in ascissa e la frequenza in ordinata.','');
INSERT INTO hardwords VALUES (22,'carreggiata','La parte della strada destinata allo scorrimento dei veicoli.','');
INSERT INTO hardwords VALUES (23,'stagno','Metallo di post-transizione argenteo e malleabile.','');
INSERT INTO hardwords VALUES (24,'innamorare','Concepire una passione amorosa per qualcuno.','');
INSERT INTO hardwords VALUES (25,'adiacenza','Luogo vicino o in prossimità.','');
INSERT INTO hardwords VALUES (26,'spinterogeno','Dispositivo per generare la scintilla.','');
INSERT INTO hardwords VALUES (27,'oltraggiare','Offendere in modo grave.','');
INSERT INTO hardwords VALUES (28,'arpeggio','Accordo musicale.','');
INSERT INTO hardwords VALUES (29,'olocausto','Genocidio perpetrato dalla Germania nazista.','');
INSERT INTO hardwords VALUES (30,'chilometro',"E' un unita di lunghezza del Sistema Internazionale.",'');
INSERT INTO hardwords VALUES (31,'ocarina','Strumento musicale popolare a fiato.','');
INSERT INTO hardwords VALUES (32,'pellicano','Genere di uccelli acquatici.','');
INSERT INTO hardwords VALUES (33,'tappezzeria','La tecnica di arte-artigianato di rivestimento di pareti.','');
INSERT INTO hardwords VALUES (34,'abluzione','Lavanda sommaria del corpo.','');
INSERT INTO hardwords VALUES (35,'accomiata','Dare commiato, lincenziare, congedare.','');
INSERT INTO hardwords VALUES (36,'nichel',"Elemento chimico usato solitamente per l'acciaio.",'');
INSERT INTO hardwords VALUES (37,'antico','Risalente a tempi remoti.','');
INSERT INTO hardwords VALUES (38,'paffuto','Grassoccio, detto per lo più dei bambini sani e ben nutriti.','');
INSERT INTO hardwords VALUES (39,'straordinario','Non ordinario, fuori dalla norma.','');
INSERT INTO hardwords VALUES (40,'sentimento','Momento della vita interiore, pertinente al mondo delle emozioni.','');
INSERT INTO hardwords VALUES (41,'nuraghe','Tipo di costruzione sarda in pietra.','');
INSERT INTO hardwords VALUES (42,'costruzione','Ideare ed eseguire, fabbricare un manufatto.','');
INSERT INTO hardwords VALUES (43,'necropoli','Agglomerato di tombe.','');
INSERT INTO hardwords VALUES (44,'acustico',"Serve a migliorare o correggere le facoltà dell'udito.",'');
INSERT INTO hardwords VALUES (45,'additare','Mostrare con il dito.','');
INSERT INTO hardwords VALUES (46,'clausola','Condizione di un contratto.','');
INSERT INTO hardwords VALUES (47,'divaricatore','Utilizzato nelle operazioni chirurgiche per allargare i lembi di una ferita.','');
INSERT INTO hardwords VALUES (48,'abiurato','Rigetto di una precedente ideologia.','');
INSERT INTO hardwords VALUES (49,'capriccio','Voglia improvvisa e stravagante.','');
INSERT INTO hardwords VALUES (50,'trinciante','Coltello per tagliare grossi pezzi di carne.','');
INSERT INTO hardwords VALUES (51,'originario','Che proviene da un luogo determinato.','');
INSERT INTO hardwords VALUES (52,'occhiaia','Cavità oculare del cranio.','');
INSERT INTO hardwords VALUES (53,'disinfettante','Misura atta a ridurre la maggior quantità di microrganismi.','');
INSERT INTO hardwords VALUES (54,'paradisiaco','Luogo ameno e incantevole.','');
INSERT INTO hardwords VALUES (55,'chitarra','Strumento musicale cordofono.','');
INSERT INTO hardwords VALUES (56,'asciugamano','Panno usato per asciugarsi dopo essersi lavati.','');
INSERT INTO hardwords VALUES (57,'uliva',"Il frutto dell'olivo",'');
INSERT INTO hardwords VALUES (58,'schiantare','Rompere in modo violento, istantaneo.','');
INSERT INTO hardwords VALUES (59,'assicurazione','Rendere sicuro qualcuno o qualcosa.','');
INSERT INTO hardwords VALUES (60,'ominide','Famiglia di primati.','');
INSERT INTO hardwords VALUES (61,'orbitare',"Descrivere un'orbita intorno a un altro corpo.",'');
INSERT INTO hardwords VALUES (62,'patriottico',"Ispirato alla difesa o all'esaltazione della patria.",'');
INSERT INTO hardwords VALUES (63,'nodulare','Struttura innaturale.','');
INSERT INTO hardwords VALUES (64,'sbandare','Deviare improvvisamente e accidentalmente dal normale assetto di marcia.','');
INSERT INTO hardwords VALUES (65,'difficile','Che richiede notevole sforzo, abilità, attenzione o applicazione mentale.','');
INSERT INTO hardwords VALUES (66,'pediluvio','Trattamento idroterapico.','');
INSERT INTO hardwords VALUES (67,'deragliare','Uscire dalle rotaie.','');
INSERT INTO hardwords VALUES (68,'parteggiare','Militare in un partito o in una fazione.','');
INSERT INTO hardwords VALUES (69,'avanzare','Andare avanti, procedere.','');
INSERT INTO hardwords VALUES (70,'depuratore',"Dispositivo che serve per eliminare impurità dall'acqua.",'');
INSERT INTO hardwords VALUES (71,'negligente','Svogliato nei propri doveri.','');
INSERT INTO hardwords VALUES (72,'terme','Complesso di edifici dotato di attrezzature atte a sfruttare le acque termominerali.','');
INSERT INTO hardwords VALUES (73,'obiettore','Chi muove obiezioni.','');
INSERT INTO hardwords VALUES (74,'origliare','Stare in ascolto di nascosto.','');
INSERT INTO hardwords VALUES (75,'motociclo','Veicolo a due ruote spinto da un motore.','');
INSERT INTO hardwords VALUES (76,'acustica','Branca della fisica che studia il suono.','');
INSERT INTO hardwords VALUES (77,'pecoreccio','Senso di goffaggine o volarità.','');
INSERT INTO hardwords VALUES (78,'percezione','La percezione è il processo psichico che opera la sintesi dei dati sensoriali.','');
INSERT INTO hardwords VALUES (79,'ovale','Che ha forma simile a un uovo.','');
INSERT INTO hardwords VALUES (80,'candelabro','Oggetto con la funzione di reggere le candele.','');
INSERT INTO hardwords VALUES (81,'salpare',"Levare l'ancora, sciogliere gli ormeggi e partire",'');
INSERT INTO hardwords VALUES (82,'spolverino','Arnese per spolverare, per levare la polvere.','');
INSERT INTO hardwords VALUES (83,'addensare','Rendere più densa una sostanza.','');
INSERT INTO hardwords VALUES (84,'numerologia','Disciplina che studia il significato dei numeri.','');
INSERT INTO hardwords VALUES (85,'sacca','Grossa borsa per trasportare effetti personali o altro.','');
INSERT INTO hardwords VALUES (86,'ossario','Nei cimiteri, edificio in cui sono raccolte le ossa.','');
INSERT INTO hardwords VALUES (87,'abbagliante','Di luminosità intensa e brillante.','');
INSERT INTO hardwords VALUES (88,'obiettare','Contestare a quanto detto o proposto.','');
INSERT INTO hardwords VALUES (89,'accasciare','Cadere giù, abbattere.','');
INSERT INTO hardwords VALUES (90,'svoltare','Curvare, cambiare direzione.','');
INSERT INTO hardwords VALUES (91,'obsoleto','Antiquato, sorpassato.','');
INSERT INTO hardwords VALUES (92,'accigliato','Con le sopracciglia aggrottate.','');
INSERT INTO hardwords VALUES (93,'pergolato','Impalcatura di sostegno per piante rampicanti e viti.','');
INSERT INTO hardwords VALUES (94,'ammuffire','Guastarsi per la muffa.','');
INSERT INTO hardwords VALUES (95,'ostrogoto','Rozzo, incivile e incomprensibile.','');
INSERT INTO hardwords VALUES (96,'davanzale','Lastra o tavola che copre il parapetto delle finestre.','');
INSERT INTO hardwords VALUES (97,'biforcazione','Divisione in due parti di qualcosa.','');
INSERT INTO hardwords VALUES (98,'abbreviato','Rendere qualcosa più breve o più corto.','');
INSERT INTO hardwords VALUES (99,'eccesso','Quantità eccessiva di qualcosa.','');
INSERT INTO hardwords VALUES (100,'sgombro','Libero da ingombri, da ostacoli.','');
INSERT INTO hardwords VALUES (101,'funzione','Particolare attività o compito svolti in un dato ambito.','');
INSERT INTO hardwords VALUES (102,'penicellina','Antibiotico beta-lattamici.','');
INSERT INTO hardwords VALUES (103,'onirologia','Lo studio dei sogni.','');
INSERT INTO hardwords VALUES (104,'labbro',"Ciascuna delle due pieghe cutanee che delimitano l'apertura della bocca.",'');
INSERT INTO hardwords VALUES (105,'stantio',"Privo di attualità o d'interesse.",'');
INSERT INTO hardwords VALUES (106,'slargo','Punto in cui una strada si allarga.','');
INSERT INTO hardwords VALUES (107,'bisognare','Con soggetto posposto, essere necessario a qualcuno.','');
INSERT INTO hardwords VALUES (108,'accasare','Far sposare qualcuno.','');
INSERT INTO hardwords VALUES (109,'oculare',"Relativo all'occhio.",'');
INSERT INTO hardwords VALUES (110,'cortile','Area libera, scoperta.','');
INSERT INTO hardwords VALUES (111,'peccaminoso','Comportamento vizioso e colpevole.','');
INSERT INTO hardwords VALUES (112,'accasata','Far sposare qualcuno.','');
INSERT INTO hardwords VALUES (113,'sgabello','Sedile per una sola persona.','');
INSERT INTO hardwords VALUES (114,'omettere','Tralasciare qualcosa intenzionalmente.','');
INSERT INTO hardwords VALUES (115,'foratura','Esecuzione di uno o più fori.','');
INSERT INTO hardwords VALUES (116,'riguardare','Guardare di nuovo qualcosa o qualcuno.','');
INSERT INTO hardwords VALUES (117,'ingorgo','Rallentamento nel deflusso di un liquido.','');
INSERT INTO hardwords VALUES (118,'candeliere','Sostegno per una sola candela.','');
INSERT INTO hardwords VALUES (119,'parabrezza','Elemento anteriore dei veicoli.','');
INSERT INTO hardwords VALUES (120,'strapazzare','Trattare in malo modo.','');
INSERT INTO hardwords VALUES (121,'opinione','Idea, giudizio individuale, punto di vista soggettivo.','');
INSERT INTO hardwords VALUES (122,'abiurata','Rigetto di una precedente ideologia.','');
INSERT INTO hardwords VALUES (123,'guardia','Mansione di chi veglia su cose e persone.','');
INSERT INTO hardwords VALUES (124,'adulazione','Atteggiamento di chi asseconda, lusinga o corteggia.','');
INSERT INTO hardwords VALUES (125,'ornitorinco','Mammifero oviparo della famiglia dei Monotremi.','');
INSERT INTO hardwords VALUES (126,'orefice','Chi vende oggetti di oreficeria.','');
INSERT INTO hardwords VALUES (127,'omologare','Approvare un oggetto ritenuto a norma di legge.','');
INSERT INTO hardwords VALUES (128,'indaco','Colorante di orgine vegetale.','');
INSERT INTO hardwords VALUES (129,'origami','Ottenere, piegando carta, figure o oggetti.','');
INSERT INTO hardwords VALUES (130,'percussione','Strumento musicale che suona quando percosso.','');
INSERT INTO hardwords VALUES (131,'imbarcare',"Far salire qualcuno o qualcosa su un'imbarcazione o un aereo.",'');
INSERT INTO hardwords VALUES (132,'parafrasi','Consiste in una “traduzione” di un testo poetico.','');
INSERT INTO hardwords VALUES (133,'accogliere','Ricevere qualcuno o qualcosa.','');
INSERT INTO hardwords VALUES (134,'abbondo','Essere presente in grande numero o quantità.','');
INSERT INTO hardwords VALUES (135,'qualsiasi','Tutti i possibili, tutte le possibili.','');
INSERT INTO hardwords VALUES (136,'patriarcale','Relativo al patriarca, come capo famiglia.','');
INSERT INTO hardwords VALUES (137,'rimettere','Mettere di nuovo qualcosa in un posto.','');
INSERT INTO hardwords VALUES (138,'candeggina','Soluzione di ipoclorito di sodio per uso domestico.','');
INSERT INTO hardwords VALUES (139,'omeopatia','Pratica di pseudo-medicina.','');
INSERT INTO hardwords VALUES (140,'estendere','Allargarsi territorialmente.','');
INSERT INTO hardwords VALUES (141,'abbietto','Ripugnante, spregevole.','');
INSERT INTO hardwords VALUES (142,'pagliaio','Caratteristico mucchio di paglia.','');
INSERT INTO hardwords VALUES (143,'omonimo','Che ha lo stesso nome o titolo.','');
INSERT INTO hardwords VALUES (144,'rondella','Dischetto forato che si inserisce sotto il dado di un bullone.','');
INSERT INTO hardwords VALUES (145,'provvedere','Curarsi, occuparsi di qualcuno.','');
INSERT INTO hardwords VALUES (146,'pioli','Paletto di legno.','');
INSERT INTO hardwords VALUES (147,'nicchia','Cavità ottenuta da un muro.','');
INSERT INTO hardwords VALUES (148,'finestra',"Apertura di forma regolare per consentire l'ingresso della luce.",'');
INSERT INTO hardwords VALUES (149,'maniglia','Sporgenza di varia forma applicata a porte.','');
INSERT INTO hardwords VALUES (150,'traghetto',"Trasporto, passaggio di persone o cose da una sponda all'altra",'');
INSERT INTO hardwords VALUES (151,'accasato','Far sposare qualcuno.','');
INSERT INTO hardwords VALUES (152,'acciaieria',"Impianto industriale dove si produce e si lavora l'acciaio.",'');
INSERT INTO hardwords VALUES (153,'onirico','Il sogno dal punto di vista psicanalitico.','');
INSERT INTO hardwords VALUES (154,'osmosi','Diffusione tra due liquidi miscibili.','');
INSERT INTO hardwords VALUES (155,'pavoneggiare','Compiacersi eccessivamente di se stesso.','');
INSERT INTO hardwords VALUES (156,'abbeverato','Dare da bere al bestiame.','');
INSERT INTO hardwords VALUES (157,'ortopedico','Medico specializzato in ortopedia.','');
INSERT INTO hardwords VALUES (158,'olivastro','Colore tendente al verde come le olive.','');
INSERT INTO hardwords VALUES (159,'ordinario','Che è nei limiti della norma e della regolarità.','');
INSERT INTO hardwords VALUES (160,'nutriente','Ciò che nutre aumentando la sostanza del corpo di animale o vegetale.','');
INSERT INTO hardwords VALUES (161,'obiettivo','Esente da pregiudizi, passioni, interessi soggettivi.','');
INSERT INTO hardwords VALUES (162,'abbuono','Riduzione del prezzo di una merce.','');
INSERT INTO hardwords VALUES (163,'mattatoio','Edificio per la macellazione animale.','');
INSERT INTO hardwords VALUES (164,'ovattare','Attenuare, attutire.','');
INSERT INTO hardwords VALUES (165,'medaglione','Ciondolo di metallo prezioso da portare al collo.','');
INSERT INTO hardwords VALUES (166,'pediatra','Branca della medicina che si occupa dello sviluppo psicofisico dei bambini.','');
INSERT INTO hardwords VALUES (167,'omerico','Poemi di Omero.','');
INSERT INTO hardwords VALUES (168,'stabilire','Adottare una decisione stabile e vincolante.','');
INSERT INTO hardwords VALUES (169,'raccordo','Collegamento fra due cose.','');
INSERT INTO hardwords VALUES (170,'nauseabondo','Tale da provocare la nausea.','');
INSERT INTO hardwords VALUES (171,'bruscamente','In maniera improvvisa, brusca.','');
INSERT INTO hardwords VALUES (172,'abrogato','Sopprimere una legge.','');
INSERT INTO hardwords VALUES (173,'proporre','Presentare, sottoporre qualcosa o qualcuno, alla sua attenzione.','');
INSERT INTO hardwords VALUES (174,'obbrobio','Causa di disonore, di vergogna.','');
INSERT INTO hardwords VALUES (175,'omertoso','Imposto da omertà.','');
INSERT INTO hardwords VALUES (176,'ordito',"L'insieme di fili che formano il tessuto.",'');
INSERT INTO hardwords VALUES (177,'giungere','Arrivare, pervenire in un luogo.','');
INSERT INTO hardwords VALUES (178,'cruscotto',"parete anteriore dell'abitacolo posizionata al disotto del parabrezza di un autoveicolo.",'');
INSERT INTO hardwords VALUES (179,'colossale','Di dimensioni molto grandi.','');
INSERT INTO hardwords VALUES (180,'pelandrone','Scansafatiche, fannullone.','');
INSERT INTO hardwords VALUES (181,'spremitore','Qualcosa o qualcuno che spreme.','');
INSERT INTO hardwords VALUES (182,'accomiato','Dare commiato, lincenziare, congedare.','');
INSERT INTO hardwords VALUES (183,'elevare','Rendere qualcosa più alto.','');
INSERT INTO hardwords VALUES (184,'tangenziale','Utilizzato per descrivere una strada a scorrimento veloce.','');
INSERT INTO hardwords VALUES (185,'ardesia','Varietà di argilloscisto.','');
INSERT INTO hardwords VALUES (186,'obbiettare','Chi muove obiezioni.','');
INSERT INTO hardwords VALUES (187,'scippare','Derubare qualcuno per strada.','');
INSERT INTO hardwords VALUES (188,'accalorare','Riscaldare qualcosa.','');
INSERT INTO hardwords VALUES (189,'adornare','Abbellire ornando con cura.','');
INSERT INTO hardwords VALUES (190,'abbreviata','Rendere qualcosa più breve o più corto.','');
INSERT INTO hardwords VALUES (191,'abbazia','Particolare tipo di monastero.','');
INSERT INTO hardwords VALUES (192,'pagoda','Costruzione sacra buddista a forma di torre piramidale a più piani.','');
INSERT INTO hardwords VALUES (193,'trasduttore',"Dispositivo di qualsiasi genere destinato a trasmettere dell'energia",'');
INSERT INTO hardwords VALUES (194,'psicomante','Persona dedita alla psicomanzia.','');
INSERT INTO hardwords VALUES (195,'burletta','Che non è serio, che costituisce una presa in giro.','');
INSERT INTO hardwords VALUES (196,'otaria','Leone marino sudamericano.','');
INSERT INTO hardwords VALUES (197,'rotaia',"Ognuna delle due guide d'acciaio che costituiscono il binario.",'');
INSERT INTO hardwords VALUES (198,'arrugginito','Rendere rugginoso, coprire di ruggine.','');
INSERT INTO hardwords VALUES (199,'tagliando','Parte di foglio che si stacca da un blocchetto a matrice o da una cartella.','');
INSERT INTO hardwords VALUES (200,'fusibile','Dispositivo elettrico in grado di proteggere un circuito dalle sovracorrenti.','');
INSERT INTO hardwords VALUES (201,'pargolo','Bambino di tenera età.','');
INSERT INTO hardwords VALUES (202,'pedaggio',"È una tassa per l'infrastruttura viaria.",'');
INSERT INTO hardwords VALUES (203,'mestolo','Specie di cucchiaione di legno.','');
INSERT INTO hardwords VALUES (204,'grazia','Dono profuso gratuitamente da Dio.','');
INSERT INTO hardwords VALUES (205,'abrogare','Sopprimere una legge.','');
INSERT INTO hardwords VALUES (206,'orrido','Ciò che desta orrore.','');
INSERT INTO hardwords VALUES (207,'parificazione','Operazione che rende uguali oggetti.','');
INSERT INTO hardwords VALUES (208,'facchino','Chi è addetto al trasporto di colli.','');
INSERT INTO hardwords VALUES (209,'abbagliare','Colpire qualcuno con una luce viva, offuscandogli la vista.','');
INSERT INTO hardwords VALUES (210,'slittare','Andare in slitta scivolando lungo un pendio.','');
INSERT INTO hardwords VALUES (211,'interessante','Che stimola la curiosità, il desiderio di conoscenza.','');
INSERT INTO hardwords VALUES (212,'livella',"Attrezzo utilizzato per stabilire l'orizzontalità di una retta.",'');
INSERT INTO hardwords VALUES (213,'dogana','Ufficio che esercita il controllo sulle merci che passano le frontiere di uno Stato.','');
INSERT INTO hardwords VALUES (214,'oratorio','Edificio di aggregazione cristiana.','');
INSERT INTO hardwords VALUES (215,'overdose','Dose di droga pesante.','');
INSERT INTO hardwords VALUES (216,'contadino','Chi coltiva, lavora la terra.','');
INSERT INTO hardwords VALUES (217,'turbolenza','Stato di agitazione violenta.','');
INSERT INTO hardwords VALUES (218,'ologramma','Immagine tridimensionale di un oggetto su lastra fotografica.','');
INSERT INTO hardwords VALUES (219,'adirare',"Cedere all'ira.",'');
INSERT INTO hardwords VALUES (220,'offuscare','Oscurare qualcosa, renderlo fosco.','');
INSERT INTO hardwords VALUES (221,'nausea',"Malessere che si accusa all'epigastrio e alla faringe caratterizzato da rigurgito.",'');
INSERT INTO hardwords VALUES (222,'odontoiatra','Medicina che si occupa delle patologie che colpiscono denti, gengive e ossa mascellari.','');
INSERT INTO hardwords VALUES (223,'raffermo','Non più fresco.','');
INSERT INTO hardwords VALUES (224,'patibolo',"Strumento per l'esecuzione di condanne a morte.",'');
INSERT INTO hardwords VALUES (225,'abbruno','Rendere qualcosa scuro.','');
INSERT INTO hardwords VALUES (226,'aracnide','Invertebrato, come il ragno e lo scorpione, con il capo unito al torace.','');
INSERT INTO hardwords VALUES (227,'accasciato','Cedere a terra.','');
INSERT INTO hardwords VALUES (228,'occlusione','Chiusura di un canale.','');
INSERT INTO hardwords VALUES (229,'edilizia','Tecnica, attività volta alla costruzione e alla manutenzione di edifici.','');
INSERT INTO hardwords VALUES (230,'penuria','Mancanza di cose indispensabili.','');
INSERT INTO hardwords VALUES (231,'orifizio',"Piccola apertura all'estremità di un condotto per il passaggio dei fluidi.",'');
INSERT INTO hardwords VALUES (232,'adulare','Compiacersi troppo di sé stesso.','');
INSERT INTO hardwords VALUES (233,'itinerario',"Percorso di un viaggio, di un'escursione, di una gara.",'');
INSERT INTO hardwords VALUES (234,'fanale',"Apparecchio per l'illuminazione.",'');
INSERT INTO hardwords VALUES (235,'congresso','Incontro, riunione di rappresentanti di stati per la definizione di questioni internazionali.','');
INSERT INTO hardwords VALUES (236,'orazione','Discorso solenne tenuto in pubblico.','');
INSERT INTO hardwords VALUES (237,'ciano','Uno degli inchiostri comunemente utilizzati nella stampa.','');
INSERT INTO hardwords VALUES (238,'riferire',': Riportare, raccontare ad altri quanto si è venuti a conoscere.','');
INSERT INTO hardwords VALUES (239,'astratto',"Che non deriva dall'esperienza sensibile ma dal puro ragionamento.",'');
INSERT INTO hardwords VALUES (240,'allentare','Rendere qualcosa meno stretto, meno teso.','');
INSERT INTO hardwords VALUES (241,'abiura','Rinuncia libera e perpetua.','');
INSERT INTO hardwords VALUES (242,'ammorbidente','Di sostanza usata nel lavaggio dei tessuti.','');
INSERT INTO hardwords VALUES (243,'adombrare',"Coprire d'ombra un luogo.",'');
INSERT INTO hardwords VALUES (244,'nozionismo',"Conoscenza fondata sull'apprendimento.",'');
INSERT INTO hardwords VALUES (245,'abiurare','Rinuncia libera e perpetua.','');
INSERT INTO hardwords VALUES (246,'orinare',"Eliminare l'urina dal corpo.",'');
INSERT INTO hardwords VALUES (247,'adagiare','Sdraiarsi su qualcosa.','');
INSERT INTO hardwords VALUES (248,'orfanotrofio',"Istituto per l'accoglienza e l'assistenza ai bambini orfani.",'');
INSERT INTO hardwords VALUES (249,'importare',"Introduzione nel proprio paese di merci acquistate all'estero.",'');
INSERT INTO hardwords VALUES (250,'nicotina',"Composto organico che può essere fatale per l'uomo.",'');
INSERT INTO hardwords VALUES (251,'cemento','Miscela di calcari e argille unita ad acqua.','');
INSERT INTO hardwords VALUES (252,'strofinaccio','Straccio che si usa per lavori domestici di pulizia.','');
INSERT INTO hardwords VALUES (253,'ordire','Disporre longitudinalmente i fili sul telaio.','');
INSERT INTO hardwords VALUES (254,'nettare','Secondo la mitologia classica, la bevanda degli dei.','');
INSERT INTO hardwords VALUES (255,'ulivastro','Di colore bruno tendente al verde come quello delle olive.','');
INSERT INTO hardwords VALUES (256,'nomenclatura','Denominazioni di oggetti.','');
INSERT INTO hardwords VALUES (257,'oscillatorio','Che si manifesta con oscillazioni, che ha andamento periodico.','');
INSERT INTO hardwords VALUES (258,'omeopatico',"È un sistema di medicina naturale.",'');
INSERT INTO hardwords VALUES (259,'panzerotto','Grosso raviolo ripieno di prosciutto.','');
INSERT INTO hardwords VALUES (260,'orbitale','Regione dello spazio circostante un nucleo atomico.','');
INSERT INTO hardwords VALUES (261,'improvviso','Qualcosa di imprevisto o di improvviso, imprevisto.','');
INSERT INTO hardwords VALUES (262,'cordolo','Elemento di costruzione.','');
INSERT INTO hardwords VALUES (263,'ornare','Abbellire ornando con cura.','');
INSERT INTO hardwords VALUES (264,'fenomeno',"Ciò che appare all'esperienza sensibile.",'');
INSERT INTO hardwords VALUES (265,'assumere','Prendere su di sé, accollarsi un impegno.','');
INSERT INTO hardwords VALUES (266,'abrogata','Annullare una norma con un atto.','');
INSERT INTO hardwords VALUES (267,'falsetto','Suono disconnesso, una voce, come dice il termine stesso, "falsa".','');
INSERT INTO hardwords VALUES (268,'comparto','Parte risultante da una suddivisione.','');
INSERT INTO hardwords VALUES (269,'orchessa',"Nelle fiabe, moglie dell'orco",'');
INSERT INTO hardwords VALUES (270,'suggeritore','Chi dà suggerimenti.','');
INSERT INTO hardwords VALUES (271,'oncologo','Settore della medicina che si occupa della cura dei tumori.','');
INSERT INTO hardwords VALUES (272,'oleoso','Contenente olio.','');
INSERT INTO hardwords VALUES (273,'centralina','Centrale periferica di una rete elettrica o telefonica.','');
INSERT INTO hardwords VALUES (274,'patriarca','Titolo tra i vescovi delle Chiese che accettano la successione apostolica.','');
INSERT INTO hardwords VALUES (275,'abdicato','Rinunciare formalmente ad una carica.','');
INSERT INTO hardwords VALUES (276,'compartimento','Ciascuna delle parti risultanti dalla suddivisione di uno spazio.','');
INSERT INTO hardwords VALUES (277,'impianto','Allestimento di strutture, macchinari, strumentazioni.','');
INSERT INTO hardwords VALUES (278,'oleodotto','Mezzo per il trasporto di petrolio.','');
INSERT INTO hardwords VALUES (279,'palcoscenico',"Parte dell'edificio teatrale che ospita l'azione scenica.",'');
INSERT INTO hardwords VALUES (280,'orchidea',"Fiore appartenente all'ordine delle Orchidales.",'');
INSERT INTO hardwords VALUES (281,'patriottismo','Fervido sentimento di devozione alla patria.','');
INSERT INTO hardwords VALUES (282,'patta','Apertura dei pantaloni.','');
INSERT INTO hardwords VALUES (283,'padiglione','Piccolo edificio, spesso a una sola stanza.','');
INSERT INTO hardwords VALUES (284,'fiasco','Recipiente di vetro soffiato per liquidi.','');
INSERT INTO hardwords VALUES (285,'abdicare','Rinunciare formalmente ad una carica.','');
INSERT INTO hardwords VALUES (286,'patrimonio','Definito come la ricchezza, espressa in termini monetari.','');
INSERT INTO hardwords VALUES (287,'accorgersi','Prendere coscienza di una presenza o realtà non immediata.','');
INSERT INTO hardwords VALUES (288,'addentare','Afferrare qualcosa con i denti.','');
INSERT INTO hardwords VALUES (289,'scordatura','Accordatura diversa dal normale negli strumenti ad arco.','');
INSERT INTO hardwords VALUES (290,'opificio','Stabilimento industriale per produzione di prodotti.','');
INSERT INTO hardwords VALUES (291,'obliterare','Annullare francobolli o biglietti con un timbro una stampigliatura.','');
INSERT INTO hardwords VALUES (292,'occhiello','Foro variamente orlato e rinforzato.','');
INSERT INTO hardwords VALUES (293,'tergivetro','Dispositivo automatico di pulizia del parabrezza.','');
INSERT INTO hardwords VALUES (294,'ionizzazione','Processo secondo cui atomi o molecole neutre acquistano o perdono elettroni.','');
INSERT INTO hardwords VALUES (295,'palanca','Grossa trave di legno.','');
INSERT INTO hardwords VALUES (296,'parabolico','Che ha forma di parabola.','');
INSERT INTO hardwords VALUES (297,'nespola','Frutto di due diverse piante.','');
INSERT INTO hardwords VALUES (298,'pandemia','Epidemia a rapida diffusione.','');
INSERT INTO hardwords VALUES (299,'giovanotto','Giovane ormai vicino alla maturità.','');
INSERT INTO hardwords VALUES (300,'scalpello',"Utensile d'acciaio usato per incidere.",'');
INSERT INTO hardwords VALUES (301,'partito','Organizzazione di cittadini associati che perseguono comuni finalità.','');
INSERT INTO hardwords VALUES (302,'manico','Parte di un oggetto che viene impugnata per utilizzarlo.','');
INSERT INTO hardwords VALUES (303,'abaco',"Tavoletta per calcoli in uso nell'antichità.",'');
INSERT INTO hardwords VALUES (304,'novizia','Che si prepara a prendere i voti religiosi.','');
INSERT INTO hardwords VALUES (305,'lanterna','Apparecchio per illuminazione.','');
INSERT INTO hardwords VALUES (306,'oberato','Oppresso da debiti.','');
INSERT INTO hardwords VALUES (307,'nevrosi',"Disturbo dell'adattamento",'');
INSERT INTO hardwords VALUES (308,'otite',"Infiammazione dell'orecchio medio",'');
INSERT INTO hardwords VALUES (309,'federa','Sacchetto di tela che ricopre il cuscino.','');
INSERT INTO hardwords VALUES (310,'sensore',"Dispositivo in grado di rilevare dati fisici dall'ambiente circostanze.",'');
INSERT INTO hardwords VALUES (311,'prato','Terreno agricolo inerbito per più di un anno.','');
INSERT INTO hardwords VALUES (312,'paraurti','Previene o limita i danni di una collisione a bassa velocità.','');
INSERT INTO hardwords VALUES (313,'plagio',"Attribuzione al proprio ingegno di un'opera altrui.",'');
INSERT INTO hardwords VALUES (314,'ornamento','Abbellimento ottenuto con elementi decorativi.','');
INSERT INTO hardwords VALUES (315,'ossidare',"Reazione chimica che avviene quando una sostanza o un elemento si combinano con l'ossigeno.",'');
INSERT INTO hardwords VALUES (316,'occultare','Nascondere qualcosa, sottrarlo alla vista.','');
INSERT INTO hardwords VALUES (317,'ornamentale','Destinato a fini di decorazione.','');
INSERT INTO hardwords VALUES (318,'ventosa','Materiale elastico che aderisce ad una superficie liscia.','');
INSERT INTO hardwords VALUES (319,'maestro','Insegnante di scuola elementare.','');
INSERT INTO hardwords VALUES (320,'obitorio','Stanza contenente i cadaveri.','');
INSERT INTO hardwords VALUES (321,'patire','Soffrire, provare qualcosa che comporti disagio.','');
INSERT INTO hardwords VALUES (322,'capello','Pelo della cute del capo.','');
INSERT INTO hardwords VALUES (323,'maniera','Modo in cui una cosa si manifesta.','');
INSERT INTO hardwords VALUES (324,'violino','Strumento musicale della famiglia degli archi.','');
INSERT INTO hardwords VALUES (325,'pensatoio','Luogo appartato in cui ci si ritira a meditare.','');
INSERT INTO hardwords VALUES (326,'mulattiera','Strada per il passaggio delle carovane di muli.','');
INSERT INTO hardwords VALUES (327,'istruttore',"Colui che fornisce le nozioni e l'addestramento.",'');
INSERT INTO hardwords VALUES (328,'espressione','Manifestazione di pensieri.','');
INSERT INTO hardwords VALUES (329,'oziare','Passare il tempo senza far nulla.','');
INSERT INTO hardwords VALUES (330,'oligarchia','Sistema politico in cui il governo è nelle mani di pochi potenti.','');
INSERT INTO hardwords VALUES (331,'ninfea',"Fiore acquatico che sboccia all'alba e si chiude al tramonto.",'');
INSERT INTO hardwords VALUES (332,'ciclomotore','Veicolo a 2 o 3 ruote.','');
INSERT INTO hardwords VALUES (333,'proposito','Ciò che ci si propone di fare.','');
INSERT INTO hardwords VALUES (334,'onomatopea',"Fenomeno quando i suoni di una parola descrivono l'oggetto.",'');
INSERT INTO hardwords VALUES (335,'abbrunare','Rendere qualcosa scuro','');
INSERT INTO hardwords VALUES (336,'pressione','Forza esercitata sulla superficie di un corpo.','');
INSERT INTO hardwords VALUES (337,'acquaragia','Olio essenziale di trementina.','');
INSERT INTO hardwords VALUES (338,'condizionare',"Esercitare un'azione che limita, modifica qualcosa o qualcuno.",'');
INSERT INTO hardwords VALUES (339,'cartongesso','Materiale usato in edilizia per isolare o separare ambienti.','');
INSERT INTO hardwords VALUES (340,'pagaiare','Manovrare e muovere una canoa con le pagaie.','');
INSERT INTO hardwords VALUES (341,'palpeggiare','Toccare qualcosa o qualcuno con la mano.','');
INSERT INTO hardwords VALUES (342,'regione','Ampia porzione della superficie terrestre.','');
INSERT INTO hardwords VALUES (343,'cinguettio','Canto di uccelli insistito e sommesso.','');
INSERT INTO hardwords VALUES (344,'narcotizzare','Sottoporre qualcuno ad anestesia totale.','');
INSERT INTO hardwords VALUES (345,'melodramma','Dramma interamente cantato con accompagnamento strumentale.','');
INSERT INTO hardwords VALUES (346,'paradosso','Che ha natura assurda o incredibile.','');
INSERT INTO hardwords VALUES (347,'parsimonia','Moderazione nello spendere.','');
INSERT INTO hardwords VALUES (348,'parafango','Elemento della carrozzeria, crea una connessione tra il cofano, la parte frontale e la zona delle portiere.','');
INSERT INTO hardwords VALUES (349,'algoritmo','Procedimento che risolve un determinato problema.','');
INSERT INTO hardwords VALUES (350,'abbrunato','Rendere qualcosa scuro.','');
INSERT INTO hardwords VALUES (351,'cuccetta','Lettini sovrapposti ad altri come nelle cabine di navi.','');
INSERT INTO hardwords VALUES (352,'naufragio',"Completa sommersione di un'imbarcazione",'');
INSERT INTO hardwords VALUES (353,'fantasia','Capacità della mente di inventare situazioni che non si danno nella realtà.','');
INSERT INTO hardwords VALUES (354,'paradigma','Modello di riferimento, un termine di paragone.','');
INSERT INTO hardwords VALUES (355,'omelia','Spiegazione e commento delle Sacre Scritture durante la messa.','');
INSERT INTO hardwords VALUES (356,'darsena','Un bacino acqueo artificiale.','');
INSERT INTO hardwords VALUES (357,'abbiente','In condizioni economiche agiate.','');
INSERT INTO hardwords VALUES (358,'narciso','Persona innamorata di se stessa.','');
INSERT INTO hardwords VALUES (359,'naftalina','Idrocarburo aromatico polinucleato.','');
INSERT INTO hardwords VALUES (360,'acciuga','Pesce osseo marino appartenente alla famiglia Engraulidae.','');
INSERT INTO hardwords VALUES (361,'insipido','Sgradevolmente privo di sapore.','');
INSERT INTO hardwords VALUES (362,'ombelico','Ciò che rimane della recisione praticata al cordone ombelicale.','');
INSERT INTO hardwords VALUES (363,'cinghia','Striscia minuta di fibbia, ganci o magliette, che serve a sostenere i pantaloni.','');
INSERT INTO hardwords VALUES (364,'omerale','Indumento liturgico.','');
INSERT INTO hardwords VALUES (365,'parificare','Concedere o riconoscere una parità sul piano giuridico e amministrativo.','');
INSERT INTO hardwords VALUES (366,'frizione','Organo meccanico.','');
INSERT INTO hardwords VALUES (367,'accalorata','Infervorata, eccitata.','');
INSERT INTO hardwords VALUES (368,'pagliaccio','Tipo comico tradizionale del teatro e del circo, vestito in maniera goffa.','');
INSERT INTO hardwords VALUES (369,'ormeggiare',"Fissare un'imbarcazione a uno o a più punti fermi.",'');
INSERT INTO hardwords VALUES (370,'adontare','Fare onta, offendere.','');
INSERT INTO hardwords VALUES (371,'recare','Condurre con sé un oggetto per consegnarlo a qualcuno.','');
INSERT INTO hardwords VALUES (372,'obbligazione','Impegno, dovere verso terzi.','');
INSERT INTO hardwords VALUES (373,'ombelicale',"Relativo all'ombelico.",'');
INSERT INTO hardwords VALUES (374,'abrasione','Lesione superficiale della pelle.','');
INSERT INTO hardwords VALUES (375,'accalorato','Infervorato, eccitato.','');
INSERT INTO hardwords VALUES (376,'obbiettore','Chi rifiuta di ottemperare a obblighi imposti dal diritto.','');
INSERT INTO hardwords VALUES (377,'pizzicato','Tecnica usata per suonare gli strumenti ad arco.','');
INSERT INTO hardwords VALUES (378,'fetecchia','Cosa o persona di nessun valore.','');
INSERT INTO hardwords VALUES (379,'sterzare','Manovrare lo sterzo per cambiare direzione.','');
INSERT INTO hardwords VALUES (380,'obbiettivo',"Che si fonda sull'analisi della realtà.",'');
INSERT INTO hardwords VALUES (381,'pazzesco','Tipico o degno di un pazzo.','');
INSERT INTO hardwords VALUES (382,'orzata','Utilizzato per designare genericamente molti tipi di bevande rinfrescanti.','');
INSERT INTO hardwords VALUES (383,'ordigno','Congegno dal meccanismo complicato.','');
INSERT INTO hardwords VALUES (384,'nocivo','Che provoca un danno di varia natura o entità.','');
INSERT INTO hardwords VALUES (385,'adulatore','Chi adula, lusinga.','');
INSERT INTO hardwords VALUES (386,'otorino',"Ramo della medicina riguardante malattie dell'orecchio, del naso e della gola.",'');
INSERT INTO hardwords VALUES (387,'paganesimo','Quelle religioni viste in opposizione al cristianesimo.','');
INSERT INTO hardwords VALUES (388,'acquietare','Ricondurre a uno stato di quiete.','');
INSERT INTO hardwords VALUES (389,'ossidiana','Vetro vulcanico che ha origine dal veloce raffreddamento di lave ricche di silicio.','');
INSERT INTO hardwords VALUES (390,'notabile','Notevole, degno di nota.','');
INSERT INTO hardwords VALUES (391,'peperone',"Pianta erbacea originaria dell'America tropicale.",'');
INSERT INTO hardwords VALUES (392,'sparecchiare',"Liberare la tavola di tutto ciò che l'ingombra.",'');
INSERT INTO hardwords VALUES (393,'abbeverata','Dare da bere al bestiame.','');
INSERT INTO hardwords VALUES (394,'oltranza','Superamento del limite consentito o conveniente.','');
INSERT INTO hardwords VALUES (395,'palmento',"Luogo in cui avveniva la pigiatura dell'uva.",'');
INSERT INTO hardwords VALUES (396,'natica','Ciascuna delle due masse carnose sporgenti posteriormente.','');
INSERT INTO hardwords VALUES (397,'coadiuvare','Aiutare qualcuno o qualcosa.','');
