INSERT INTO mediumwords(ID, Word, Meaning, Category) VALUES
(1,"atteggiamento","Modo di disporsi o di presentarsi.",''),
(2,"paraurti","Parte della carrozzeria di un veicolo la cui funzione è quella di prevenire o limitare i danni di una collisione.",''),
(3,"oggettivo","Aderente alla realtà dei fatti, non influenzato da pregiudizi.",''),
(4,"nozze","Il rito, la cerimonia con cui si celebra il matrimonio.",''),
(5,"sforzare","Sottoporre a uno sforzo intenso o eccessivo.",''),
(6,"movimento","L'azione del muovere o del muoversi.",''),
(7,"produrre","Comporre, ideare, creare opere dell’ingegno.",''),
(8,"nucleare","Tutti quei fenomeni in cui si ha produzione di energia in seguito a trasformazioni nei nuclei atomici.",''),
(9,"lasciare","Allontanarsi da una persona o da un luogo.",''),
(10,"adattare","Rendere qualcosa adatto a uno scopo.",''),
(11,"staccare","Separare una cosa da un'altra.",''),
(12,"navigatore","Colui che naviga anche nel Mar Rosso.",''),
(13,"acustica","Branca della fisica che studia il suono.",''),
(14,"oscillare","Muoversi fra due posizioni estreme.",''),
(15,"oggetto","Entità fisica.",''),
(16,"avvocato","Professionista delegato ad assistere e difendere una parte in un giudizio.",''),
(17,"pennino","Parte scrivente della penna.",''),
(18,"militare","Appartenente alle forze armate.",''),
(19,"ufficiale","Specifica posizione gerarchica militare.",''),
(20,"conservare","Tenere con cura un oggetto o un bene.",''),
(21,"attendere","Aspettare.",''),
(22,"pastoso","Consistenza molle come pasta.",''),
(23,"panoramico","Vedere un ampio panorama, che offre una gradevole vista.",''),
(24,"occhiata","Pesce d'acqua salata appartenente alla famiglia degli Sparidi.",''),
(25,"ostinare","Persistere tenacemente in un atteggiamento.",''),
(26,"traversata","Passaggio attraverso un ambito spaziale di notevole estensione.",''),
(27,"collaboratore","Chi partecipa attivamente a un'impresa.",''),
(28,"successo","Esito favorevole.",''),
(29,"abbocca","Afferrare con la bocca.",''),
(30,"saporito","Ricco di sapore.",''),
(31,"contare","Valutare quantitativamente un insieme attribuendo i numeri in ordine progressivo.",''),
(32,"ozono","Molecola che consiste in tre atomi di ossigeno negativamente caricati.",''),
(33,"naturale","Atteggiamenti spontanei.",''),
(34,"adattato","Rendere qualcosa adatto a uno scopo.",''),
(35,"pegno","Diritto concesso su un bene mobile dal debitore o da un terzo.",''),
(36,"camicia","Indumento con maniche lunghe o corte e con colletto.",''),
(37,"elettrico","Relativo all'elettricità, alla sua produzione e al suo sfruttamento.",''),
(38,"ovatta","Semilavorato tessile simile al feltro, soffice e di scarsa consistenza.",''),
(39,"adesivo","Determina o consente adesione.",''),
(40,"tratto","Linea tracciata con un unico e rapido movimento.",''),
(41,"abbondato","Esagerare in qualcosa.",''),
(42,"motorino","Piccolo motore elettrico.",''),
(43,"sacrificio","Privazione, rinuncia, disagio imposto da determinate condizioni.",''),
(44,"chiesa","Edificio consacrato al culto cristiano.",''),
(45,"polizia","Organo del potere esecutivo dello Stato.",''),
(46,"fogne","Canali sotterranei per la raccolta e l'eliminazione delle acque putride.",''),
(47,"martello","Utensile costituito da un massello metallico di un certo peso, con un occhio al centro, nel quale è inserito un manico che ne consente l'impugnatura.",''),
(48,"interesse","Compenso che si versa o si riscuote per il prestito di un capitale.",''),
(49,"trapano","Macchina utensile che lavora in modo rotatorio praticando fori cilindrici mediante una punta opportunamente sagomata.",''),
(50,"parecchio","In numero o quantità notevole.",''),
(51,"pasticcio","Simbolo di disordine o confusione.",''),
(52,"smettere","Sospendere temporaneamente o definitivamente.",''),
(53,"ordinamento","Complesso di norme che disciplinano una determinata istituzione o attività.",''),
(54,"accertato","Rendere certo, assicurare.",''),
(55,"sangue","Fluido biologico circolante nei Vertebrati, sotto l'impulso dell'attività cardiaca.",''),
(56,"penultimo","Precede immediatamente l'ultimo.",''),
(57,"parafulmine","Sistema di protezione di edifici dalle scariche atmosferiche.",''),
(58,"padrone","Proprietario di qualcosa.",''),
(59,"invitare","Proporre la partecipazione, offrire ospitalità.",''),
(60,"principale","Maggior rilievo, maggior importanza.",''),
(61,"fatica","Sforzo prolungato che porta all'indebolimento della resistenza fisica.",''),
(62,"occhio","Organo di senso per la ricezione degli stimoli luminosi.",''),
(63,"rivoluzione","Movimento organizzato e violento col quale si instaura un nuovo ordine sociale o politico.",''),
(64,"onnipotenza","Potere di fare tutto, senza alcun limite.",''),
(65,"postura","Posizione del corpo umano nello spazio.",''),
(66,"obbligare","Imporre un comportamento, costringere.",''),
(67,"autobus","Autoveicolo attrezzato per il trasporto collettivo di persone su percorsi urbani e suburbani.",''),
(68,"motore","Macchina che trasforma una determinata forma di energia in energia meccanica.",''),
(69,"orfano","Persona che ha perso uno od entrambi i genitori.",''),
(70,"manuale","Libro che riporta, con criteri informativi e didattici, le nozioni fondamentali relative a un argomento.",''),
(71,"repubblica","Forma di governo in cui tutti i cittadini dello Stato partecipano al potere supremo.",''),
(72,"panino","Piccola forma di pane, per lo più tonda od ovale.",''),
(73,"nuocere","Arrecare danno materiale o morale.",''),
(74,"maiale","Mammifero della famiglia dei Suini.",''),
(75,"attaccare","Assalire in forze.",''),
(76,"gusto","Senso che permette la definizione qualitativa di una sostanza in base al sapore.",''),
(77,"parcheggio","Spazio riservato alla sosta per i veicoli.",''),
(78,"pallottola","Sfera di limitate dimensioni, costituita di materia compatta.",''),
(79,"ostello","Albergo per il pernottamento temporaneo ed economico.",''),
(80,"teiera","Recipiente di materiale vario, per lo più di forma panciuta e con beccuccio.",''),
(81,"controllo","Esame condotto allo scopo di garantire la regolarità.",''),
(82,"orgoglioso","Forte senso di autostima e fiducia nelle proprie capacità.",''),
(83,"panorama","Ampia veduta generale da un punto sopraelevato.",''),
(84,"veicolo","Mezzo meccanico di trasporto guidato.",''),
(85,"minimo","La quantità più piccola possibile.",''),
(86,"mattina","Parte del giorno compresa tra l'alba e mezzogiorno.",''),
(87,"mancare","Essere assente o essere presente in quantità scarsa o insufficiente.",''),
(88,"slancio","Proiezione impetuosa del corpo in avanti, in alto o in basso.",''),
(89,"nozione","Dato elementare di una conoscenza specifica.",''),
(90,"colpa","Atto o comportamento che implica conseguenze dannose.",''),
(91,"fondo","La parte terminale inferiore di un recipiente o di una cavità.",''),
(92,"pastorizzare","Processo di risanamento termico applicato ad alcuni alimenti allo scopo di minimizzare i rischi per la salute.",''),
(93,"esporre","Offrire alla vista o all'attenzione altrui, mettere in mostra.",''),
(94,"parentesi","Interrompere la continuità di un discorso,per lo più a scopo di chiarimento o di precisazione.",''),
(95,"adocchiare","Guardare qualcosa, qualcuno con interesse.",''),
(96,"dichiarare","Manifestare, esporre in termini espliciti.",''),
(97,"pacare","Acquietare, calmare.",''),
(98,"assistente","Chiamato ad aiutare tecnicamente il responsabile di varie attività.",''),
(99,"organico","Riguardante gli organi degli esseri viventi.",''),
(100,"sonno","Stato di riposo contrapposto alla veglia. ",''),
(101,"riparare","Azione, opera volta a risarcire un danno materiale o morale.",''),
(102,"necessario","Indispensabile o almeno estremamente utile per ottenere certi scopi.",''),
(103,"pentimento","Il riconoscimento di una propria colpa, atteggiamento di autocondanna.",''),
(104,"tegola","Materiale da costruzione usato per la copertura delle falde inclinate dei tetti.",''),
(105,"abbasso","Espressione di ostilità.",''),
(106,"accostare","Avvicinare per chiedere o comunicare qualcosa.",''),
(107,"azzurro","Colore intermedio tra il celeste e il blu.",''),
(108,"abituale","Corrispondente a un'abitudine",''),
(109,"multa","Sanzione penale stabilita dalla legge o da un regolamento contrattuale.",''),
(110,"guidare","Precedere qualcuno per indicargli la strada, Condurre un autoveicolo.",''),
(111,"accentrato","Gruppo di persone radunate insieme in uno stesso luogo.",''),
(112,"videogioco","Gioco gestito da un dispositivo elettronico che consente di interagire con le immagini di uno schermo.",''),
(113,"ragione","Facoltà per mezzo della quale si esercita il pensiero.",''),
(114,"preparare","Disporre, sistemare qlco. in modo che sia pronto per l'uso richiesto.",''),
(115,"industria","Attività umana che viene svolta allo scopo di generare beni o servizi.",''),
(116,"sport"," L'insieme delle attività, che impegnano determinate capacità psicomotorie.",''),
(117,"segretario","Incaricato di mansioni varie e riservate per conto di altra persona.",''),
(118,"serenata","Canto con accompagnamento musicale, eseguito di sera sotto la casa della donna amata per renderle omaggio.",''),
(119,"alloggiare","Accogliere, ospitare qualcuno in un luogo.",''),
(120,"addetto","Assegnato a un determinato compito o ufficio.",''),
(121,"prezzo","Valore economico di un bene o servizio.",''),
(122,"palpebra","Pieghe cutanee mobili che, avvicinandosi coprono la parte anteriore del globo oculare.",''),
(123,"pascolo","Terreno coperto di erbe riservate direttamente all'alimentazione del bestiame.",''),
(124,"palese","Che appare chiaro, indubitabile, evidente.",''),
(125,"numeratore","Numero sopra la linea di frazione.",''),
(126,"portorico","Territorio non incorporato degli Stati Uniti d'America, situato nel nord-est del mar dei Caraibi.",''),
(127,"abboccata","Farsi imbrogliare da qualcuno.",''),
(128,"felice","Sereno, appagato, completamente soddisfatto.",''),
(129,"passaggio","Transito attraverso un luogo o spostamento da un luogo all'altro.",''),
(130,"conseguenza","Conclusione dedotta logicamente da una premessa.",''),
(131,"ombrello","Riparo portatile contro la pioggia, o anche contro il sole.",''),
(132,"viaggiare","Spostarsi da un luogo a un altro compiendo un percorso.",''),
(133,"rientrare","Entrare di nuovo in un luogo da cui si era usciti.",''),
(134,"sviluppo","Accrescimento progressivo.",''),
(135,"nominativo","Nel linguaggio burocratico, nome di persona.",''),
(136,"rivelare","Rendere note cose sconosciute.",''),
(137,"pallavolo","Gioco che si disputa tra due squadre di sei giocatori ciascuna in un campo diviso in due parti da una rete.",''),
(138,"specchio","Lastra di vetro, metallizzata su una faccia, che riflette la luce e le immagini.",''),
(139,"recente","Risale a poco tempo addietro, accaduto, manifestatosi da poco.",''),
(140,"abolisco","Rendere nullo, non fare più uso.",''),
(141,"commerciare","Esercitare il commercio di determinati prodotti.",''),
(142,"obbligo","Vincolo giuridicamente o moralmente previsto e imposto.",''),
(143,"osannare","Esaltata venerazione.",''),
(144,"distruggere","Abbattere, disfare qualcosa in modo da renderlo definitivamente inutilizzabile.",''),
(145,"comodo","Ciò che procura agio, che evita disagio.",''),
(146,"armadio","Grande mobile ad ante, con eventuali ripiani e cassetti.",''),
(147,"attento","Mente o sensi rivolti all'azione che si compie o a ciò che si ascolta.",''),
(148,"naturalmente","Per naturale conseguenza, ovviamente.",''),
(149,"arrostire","Sottoporre a cottura a fuoco vivo.",''),
(150,"classe","L'insieme delle persone che partecipano o che esercitano la stessa professione.",''),
(151,"speciale","Caratteristico di qualcosa.",''),
(152,"angolo","La parte di piano compresa tra due semirette uscenti da uno stesso punto.",''),
(153,"penalizzare","Mettere in una condizione di svantaggio, sfavorire.",''),
(154,"numerale","Qualcosa che ha rapporto coi numeri.",''),
(155,"stazione"," Luogo di arrivo e di partenza di viaggiatori e merci.",''),
(156,"peggioramento","Totale o parziale aggravamento di una situazione o condizione sfavorevole.",''),
(157,"francobollo","Cartellino di carta,recante su una faccia figure e simboli dello Stato emittente.",''),
(158,"pavone","Uccello galliforme, con piumaggio bianco o variopinto.",''),
(159,"negare","Dichiarare che un fatto non è vero.",''),
(160,"costruzione","Fase di attuazione di un'opera.",''),
(161,"ovulo","Corpicciolo di forma per lo più rotondeggiante contenente la cellula uovo.",''),
(162,"bagaglio","Il complesso degli oggetti che chi viaggia porta con sé.",''),
(163,"bicicletta","Veicolo azionato dalla forza muscolare delle gambe.",''),
(164,"accigliare","Contrarre i sopraccigli, in segno di tristezza, di severità, sdegno.",''),
(165,"medaglia","Piccolo disco di metallo, ornato da figure e scritte,per commemorare qualche avvenimento.",''),
(166,"accetta","Arnese da lavoro atto al taglio della legna.",''),
(167,"rallentare","Rendere lento.",''),
(168,"pranzare","Consumare il pranzo.",''),
(169,"stufa","Apparecchio di varia forma e materiale per riscaldare un ambiente.",''),
(170,"accentrata","Riunirsi, stabilirsi in un unico luogo.",''),
(171,"colazione","Il primo pasto del mattino.",''),
(172,"cofano","Copertura di protezione di un motore.",''),
(173,"mattino","Parte del giorno compresa tra l'alba e mezzogiorno.",''),
(174,"oracolo","Responso profetico dato da una divinità.",''),
(175,"avvertire","Acquistare coscienza di qualcosa.",''),
(176,"ormeggio","L'assicuramento di un mezzo nautico a un punto di solida presa.",''),
(177,"palude","terreno coperto d'acqua, caratterizzato dallo sviluppo di una particolare vegetazione e fauna.",''),
(178,"pasquale","Relativo alla Pasqua.",''),
(179,"opposizione","Atteggiamento contrario a qualcosa.",''),
(180,"scherzare","Comportarsi o parlare senza serietà né impegno.",''),
(181,"raccogliere","Prendere qualcosa da terra.",''),
(182,"osservare","Guardare con attenzione, esaminare.",''),
(183,"matita","Strumento per scrittura e disegno.",''),
(184,"stoviglia","Contenitori usati in cucina per contenere e servire il cibo.",''),
(185,"diffondere","Far conoscere a molte persone, divulgare.",''),
(186,"negazione","Risposta o giudizio di radicale opposizione o di rifiuto.",''),
(187,"patria","Concetto di nazione e paese.",''),
(188,"stampa","Tecnica di riproduzione in più esemplari, su carta o altro materiale, di testi scritti, disegni o fotografie.",''),
(189,"mezzo","Elemento strumentale o funzionale necessario allo svolgimento di un'azione.",''),
(190,"omicidio","Soppressione di una vita umana a opera di un altro essere umano.",''),
(191,"orecchiabile","Motivo musicale semplice e melodico.",''),
(192,"accampare","Sistemare per una permanenza all'aperto sotto tende o in alloggiamenti provvisori.",''),
(193,"colpire","Percuotere, battere, ferire con uno o più colpi.",''),
(194,"operativo","Capacità di operare.",''),
(195,"nervatura","Il complesso dei nervi, e la loro ordinata disposizione.",''),
(196,"continuare","Proseguire ininterrottamente.",''),
(197,"benzina","Miscuglio di idrocarburi liquidi utilizzato come combustibile.",''),
(198,"paternale","Grave e severo rimprovero da parte di un superiore.",''),
(199,"insistere","Protrarre a lungo con tenacia o caparbietà un'azione.",''),
(200,"operaio"," lavoratore dipendente che esegue un lavoro manuale o tecnico.",''),
(201,"tagliere","Arnese di cucina,di legno duro sul quale si taglia la carne.",''),
(202,"ventilatore","Apparecchio elettrico costituito da pale che, ruotando, creano una corrente d'aria.",''),
(203,"retromarcia","Movimento all'indietro di un veicolo.",''),
(204,"zuccheriera","Recipiente in cui si tiene o si serve lo zucchero.",''),
(205,"rompere","Spezzare un oggetto in più parti.",''),
(206,"mensola","Piano d'appoggio in legno.",''),
(207,"passione","Momento caratterizzato da uno stato di violenta e persistente emozione.",''),
(208,"lenzuolo","Telo di stoffa che si pone sul materasso.",''),
(209,"abolire","Cancellare con una disposizione dell'autorità.",''),
(210,"paletta","Piccola pala dal manico corto.",''),
(211,"abitante","Residente in uno spazio geografico determinato.",''),
(212,"onnipresenza","Il trovarsi o il potersi trovare in più luoghi nello stesso momento.",''),
(213,"disporre","Collocare secondo un certo ordine.",''),
(214,"passamontagna","Berretto a forma di cappuccio aderente che copre interamente il viso.",''),
(215,"annullare","Rendere vano, vanificare.",''),
(216,"notte","L'intervallo di tempo fra il tramontare e il sorgere del sole.",''),
(217,"posare","Mettere qualcosa in un luogo con attenzione.",''),
(218,"noleggiatore","Gestore di un'impresa per la concessione in uso temporaneo di mezzi.",''),
(219,"ottimistico","Che ha fiducia, speranza.",''),
(220,"nascondere","Riporre in luogo segreto o riparato, occultare.",''),
(221,"resto","Ciò che rimane di un insieme quando se ne tolglie una parte.",''),
(222,"limitare","Circoscrivere uno spazio entro limiti.",''),
(223,"carrello","Mezzo di sostegno o di trasporto.",''),
(224,"soldato","Presta servizio armato in un esercito.",''),
(225,"ottimo","Molto buono, buonissimo, eccellente.",''),
(226,"cotone","Pianta erbacea o arbustiva, i cui semi sono rivestiti da una peluria bianca.",''),
(227,"turista","Viaggiatore mosso da scopi di svago.",''),
(228,"ministro","Membro del governo che presiede un dicastero.",''),
(229,"addome","La parte inferiore del tronco, compresa fra torace e bacino.",''),
(230,"direttore","a persona cui fa capo la responsabilità di un'attività.",''),
(231,"impiccato","Gioco di carta e matita per due giocatori e non,chi indovina più parole senza far impiccare l'omino vince!.",''),
(232,"succoso","Ricco di succo.",''),
(233,"giustizia","Il potere pubblico di realizzare il diritto.",''),
(234,"anteriore","Precede un qualcosa nello spazio.",''),
(235,"dovere","Essere obbligati, tenuti a fare qualcosa.",''),
(236,"orientale","Situato o localizzato a oriente.",''),
(237,"paparazzo","Fotografo di attualità mondana, con una professionalità tra il furbesco e lo scandalistico.",''),
(238,"notevole","Riferito a persona, cosa o qualità, degno d'attenzione.",''),
(239,"biglietto","Letterina o foglietto con poche parole di avviso.",''),
(240,"nuotatore","Capace di nuotare o pratica lo sport del nuoto.",''),
(241,"panciata","Colpo dato con la pancia.",''),
(242,"sbarcare","Fare scendere persone o cose da un'imbarcazione.,",''),
(243,"penetrare","Entrare in qualcosa che oppone resistenza.",''),
(244,"parabola","Figura piana di una particolare sezione conica.",''),
(245,"chiamare","Interpellare qualcuno con la voce, spesso accompagnata da gesti o segnali.",''),
(246,"tariffa","Prezzo di un servizio fissato da un'autorità, ente o imprese pubbliche.",''),
(247,"misura","Rapporto tra una grandezza e un'altra omogenea.",''),
(248,"oppressore","Responsabile di continue sopraffazioni.",''),
(249,"prova","Accertamento, attraverso specifiche operazioni, delle proprietà, della qualità, di qualcosa.",''),
(250,"cartina","Carta geografica o topografica di piccolo formato o ripiegabile.",''),
(251,"paterno","Riferibile al padre, a lui appartenente.",''),
(252,"moderno","Relativo e proprio del momento attuale.",''),
(253,"notaio","Pubblico ufficiale il cui compito specifico è quello di ricevere gli atti, conservarne il deposito, rilasciarne copie.",''),
(254,"modulo"," In genere, misura, forma, esemplare, che si assume come modello a cui attenersi.",''),
(255,"normanno","Abitante, nativo della Normandia.",''),
(256,"forno","Impianto per la cottura.",''),
(257,"rumoroso","Produce o comporta eccessivo rumore.",''),
(258,"onore","Buona reputazione, rispettabilità di chi si comporta con onestà.",''),
(259,"dividere","Scomporre in più parti.",''),
(260,"ossigenato","Contenente ossigeno.",''),
(261,"obeso","Condizione medica caratterizzata da un eccessivo accumulo di grasso.",''),
(262,"orizzontale","Parallelo al piano dell'orizzonte.",''),
(263,"sedile","Qualsiasi mobile o struttura su cui si possa stare seduti.",''),
(264,"nuvola","Nube che si forma negli strati alti dell'atmosfera.",''),
(265,"civile","Riguarda la comunità organizzata e dei rapporti tra i membri che la compongono.",''),
(266,"temperatura","Grandezza che misura gli scambi di calore tra corpi in contatto termico.",''),
(267,"sofferenza","Condizione tormentosa provocata dall'assiduità del dolore.",''),
(268,"accaduta","Cosa accaduta,avvenimento, evento.",''),
(269,"orafo","Artigiano che esegue lavori in oro e in altri metalli preziosi.",''),
(270,"orribile","Ciò che provoca orrore.",''),
(271,"televisore","Apparecchio per la ricezione dei programmi televisivi.",''),
(272,"istituto","Ente pubblico o privato istituito per perseguire fini di interesse generale.",''),
(273,"pallido","Sbiancato nel colorito.",''),
(274,"abisso","Luogo cui la profondità conferisce un aspetto misterioso o pauroso.",''),
(275,"ferire","Colpire causando una ferita.",''),
(276,"ombrellone","Ombrello di grandi dimensioni,in genere adoperato per ripararsi dal sole sulle spiagge.",''),
(277,"trattore","Automezzo agricolo capace di sviluppare un elevato sforzo di trazione.",''),
(278,"paralizzare","Rendere incapace di muoversi o di reagire.",''),
(279,"nodoso","Caratterizzato da uno o più nodi.",''),
(280,"lampada","Sorgente di luce artificiale.",''),
(281,"abbozzare","Realizzare in forma preliminare o provvisoria.",''),
(282,"isola","Limitata porzione di terraferma completamente circondata dalle acque.",''),
(283,"pennarello","Tipo di penna con pennino in feltro o in nylon.",''),
(284,"decidere","Scegliere tra cose o possibilità.",''),
(285,"abbiglio","Vestire una persona con particolare cura ed eleganza.",''),
(286,"molletta","Piccolo arnese a molla per fermare o per appuntare qualcosa.",''),
(287,"abbigliamento","L'insieme degli oggetti di vestiario.",''),
(288,"assistere","Aiutare, confortare con la propria presenza e partecipazione.",''),
(289,"accusa","L'atto, le parole, con cui si attribuisce a qualcuno una colpa.",''),
(290,"accurato","Condotto o realizzato con precisione e competenza.",''),
(291,"giudicare","Formulare un giudizio di valore, un'opinione su qualcuno o qualcosa.",''),
(292,"passeggero","Colui che è di passaggio.",''),
(293,"grigio","Colore intermedio tra il bianco e il nero.",''),
(294,"signorina","Titolo di cortesia attribuito a donne nubili.",''),
(295,"seguito","Gruppo di persone che fanno scorta o compagnia.",''),
(296,"ossesso","Pensiero che ritorna continuamente e in modo tormentoso.",''),
(297,"passero","Piccolo uccello molto comune, con becco forte e conico.",''),
(298,"accelerato","Aumento di velocità o è più frequente del normale.",''),
(299,"forza","Qualsiasi causa capace di modificare lo stato di quiete o di moto di un corpo.",''),
(300,"agitare","Muovere in qua e in là rapidamente e con forza.",''),
(301,"addobbare","Ornare con paramenti, decorazioni.",''),
(302,"credenza","Mobile in cui si tengono stoviglie, posaterie, bicchieri.",''),
(303,"accertare","Rendere certo, assicurare.",''),
(304,"parziale","Relativo a una frazione limitata.",''),
(305,"cassaforte","Robusto armadio, spesso blindato.",''),
(306,"numeroso","Costituito da un numero notevole di elementi.",''),
(307,"peccato","Fatto o esperienza variamente condannabile.",''),
(308,"aereo","D'aria, formato o costituito di aria.",''),
(309,"ossessione","Motivo grave e persistente di preoccupazione o di molestia.",''),
(310,"numerico","Relativo alla presenza o all'uso funzionale dei numeri.",''),
(311,"perdere","Non riuscire più a ritrovare, smarrire.",''),
(312,"animazione","Conferimento di vita, di movimento.",''),
(313,"processo","Successione di fatti o fenomeni aventi tra loro un collegamento.",''),
(314,"accentuato","Di notevole intensità o evidenza.",''),
(315,"commissione","Incarico affidato a qualcuno.",''),
(316,"parassita","Organismo che vive parzialmente o totalmente a spese di un altro individuo.",''),
(317,"pianoforte","Strumento musicale a corde percosse da martelletti azionati per mezzo di una tastiera.",''),
(318,"abbracci","Gesti affettuosi.",''),
(319,"promettere","Impegnarsi a fare o dare qualcosa.",''),
(320,"pasticcino","Piccolo dolcetto che si offre soprattutto con il tè.",''),
(321,"parigino","Abitante, nativo di Parigi.",''),
(322,"parametro","Una costante arbitraria.",''),
(323,"offendere","Arrecare un danno morale a qualcuno pronunciando parole o compiendo atti che offendono la sua dignità.",''),
(324,"accelerare","Diventare più veloce.",''),
(325,"pinzetta","Pinze di dimensioni ridotte.",''),
(326,"principiante","Chi è alle prime armi nell'apprendimento.",''),
(327,"apparire","Mostrarsi alla vista.",''),
(328,"nutrire","Fornire degli alimenti necessari al sostentamento.",''),
(329,"scienza","Sistema di conoscenze ottenute attraverso un'attività di ricerca.",''),
(330,"portone","Porta di dimensioni rilevanti.",''),
(331,"ricchezza","Larga disponibilità di beni e di denaro.",''),
(332,"primavera","Stagione dell'anno.",''),
(333,"prato","Terreno ricoperto da erbe.",''),
(334,"parchimetro","Apparecchio situato vicino a un parcheggio a tariffa.",''),
(335,"capace","In grado di fare qualcosa.",''),
(336,"villa","Tipo di abitazione ampia ed elegante.",''),
(337,"pandoro","Dolce natalizio tipico veronese.",''),
(338,"amatoriale","Attività svolta per puro diletto.",''),
(339,"acquirente","La persona che acquista mediante compera.",''),
(340,"possibile","Ciò che può essere, esistere, accadere.",''),
(341,"confezione","Preparazione di merci e prodotti per la vendita.",''),
(342,"ristorante","Locale pubblico nel quale si servono pasti.",''),
(343,"riconoscere","Individuare, identificare qualcuno o qualcosa di già noto.",''),
(344,"rotonda","Costruzione di forma più o meno circolare.",''),
(345,"adeguare","Adattamento, aggiornamento.",''),
(346,"palmare","Strumento elettronico che ha dimensioni ridotte da poter essere tenuto nel palmo della mano.",''),
(347,"penetrabile","Suscettibile di penetrazione.",''),
(348,"norvegese","Abitante, nativo della Norvegia.",''),
(349,"adoratore","Chi adora.",''),
(350,"lavorare","Esercitare un'attività retribuita.",''),
(351,"spirito","Principio immateriale e immortale.",''),
(352,"oscillazione","Movimento periodico di un corpo fra due posizioni estreme.",''),
(353,"nascondiglio","Luogo angusto o appartato.",''),
(354,"origine","Momento iniziale.",''),
(355,"governo","Organo esecutivo dello stato",''),
(356,"righello","Asticella usata per tracciare linee rette.",''),
(357,"comunicazione","Notizia o dichiarazione diffusa per ragioni informative.",''),
(358,"arrestare","Fermare qualcosa bloccandone il movimento.",''),
(359,"accecato","Privare qualcuno della vista.",''),
(360,"urticante","Provoca al contatto una sensazione di irritazione.",''),
(361,"posizione","Luogo in cui qualcuno o qualcosa è posto.",''),
(362,"adocchiata","Mettere gli occhi su qualcuno o qualcosa.",''),
(363,"comporre","Mettere insieme, riunire ordinatamente.",''),
(364,"nuotare","Spostarsi in acqua con un coordinato.",''),
(365,"cacciavite","Arnese che serve per serrare o allentare le viti.",''),
(366,"tenero","Che offre scarsa resistenza alla pressione.",''),
(367,"concludere","Portare a compimento, terminare.",''),
(368,"ufficio","Compito, dovere, obbligo.",''),
(369,"malattia","Condizione anormale di un organismo.",''),
(370,"chiodo","Bastoncino metallico di varia lunghezza e spessore.",''),
(371,"compagnia","Stare insieme con altri.",''),
(372,"abbondata","Esagerare in qualcosa.",''),
(373,"riunire","Unire insieme elementi distinti.",''),
(374,"occorrere","Essere necessario a qualcuno.",''),
(375,"nautica","Scienza, arte, tecnica della navigazione.",''),
(376,"abbondare","Essere in quantità superiore al bisogno.",''),
(377,"accidia","Avversione all'operare, mista a noia e indifferenza.",''),
(378,"pagamento","Versamento, corresponsione di una somma di denaro.",''),
(379,"enorme","Di proporzioni o dimensioni molto al di là del normale.",''),
(380,"percepire","Avvertire qualcosa.",''),
(381,"aumentare","Rendere maggiore.",''),
(382,"ondulare","Ondeggiare o oscillare lievemente.",''),
(383,"corpo","Quantità di materia definita nello spazio.",''),
(384,"bloccare","Interrompere il movimento o la funzione di qualcosa.",''),
(385,"giovane","Persona di età giovanile.",''),
(386,"seggiolino","Permanenza temporanea in un luogo.",''),
(387,"ortica","Pianta erbacea perenne, con fusto e foglie ricchi di peli urticanti.",''),
(388,"adottare","Far proprio.",''),
(389,"guasto","Danno,rottura che compromette il regolare funzionamento di un sistema o macchinario.",''),
(390,"piede","Parte terminale degli arti inferiori dell'uomo.",''),
(391,"vagone","Carrozza o carro ferroviario per il trasporto di persone o merci.",''),
(392,"minore","quantità più piccola rispetto ad un'altra.",''),
(393,"rivedere","Vedere di nuovo.",''),
(394,"passeggiare","Camminare a passo lento.",''),
(395,"luogo","Parte di spazio delimitata.",''),
(396,"autonoleggio","Noleggio di automobili.",''),
(397,"coltello","Strumento da taglio.",''),
(398,"adozione","Istituto giuridico che permette di formarsi una filiazione civile.",''),
(399,"convincere","Indurre qualcuno a riconoscere la verità.",''),
(400,"autostrada","Strada a più corsie di scorrimento e senza attraversamenti.",''),
(401,"meccanico","Operaio specializzato che provvede alla riparazione e alla manutenzione di macchine.",''),
(402,"accennare","Far cenno con la mano, la testa, gli occhi.",''),
(403,"importante","Che rappresenta qualcosa di fondamentale.",''),
(404,"eseguire","Mettere in atto, dare compimento a quanto è stato disposto o prescritto.",''),
(405,"normografo","Strumento usato nel disegno tecnico per la scrittura con caratteri uniformi.",''),
(406,"decisione","Impegno definitivo assunto di fronte a una situazione.",''),
(407,"ondeggiare","Muoversi per la spinta delle onde.",''),
(408,"ringraziare","Esprimere con parole o con gesti la propria gratitudine.",''),
(409,"misterioso","Incomprensibile per l'intelletto umano.",''),
(410,"sorpassare","Portarsi oltre un dato limite, oltrepassare, varcare.",''),
(411,"ossatura","Il complesso delle ossa che costituiscono lo scheletro di un corpo.",''),
(412,"camminare","Spostarsi, procedere andando a piedi.",''),
(413,"portiere","Giocatore posto a difesa della porta.",''),
(414,"presidente","Chi, per elezione o per nomina, sovrintende a un organo collegiale.",''),
(415,"ordinanza","Atto normativo emanato da un ministro, da un prefetto o da un sindaco.",''),
(416,"carrozza","Veicolo a quattro ruote per trasporto di persone.",''),
(417,"sonata","Composizione eseguita da strumenti.",''),
(418,"orgoglio","Stima eccessiva di sé e dei propri meriti.",''),
(419,"papagallo","Uccelli esotici dalle penne multicolori e dal becco adunco.",''),
(420,"camper","Furgone attrezzato ad abitazione.",''),
(421,"onnisciente","Che dispone di una scienza illimitata.",''),
(422,"ostetrica","Infermiera che assiste le donne durante la gestazione.",''),
(423,"addentrare","Afferrare con i denti, mordere.",''),
(424,"pasticciere","Persona che provvede alla produzione di dolci.",''),
(425,"mocio","Strumento utilizzato per pulire il pavimento.",''),
(426,"marcire","Diventare marcio, guastarsi, putrefarsi.",''),
(427,"convenienza","Adeguatezza, corrispondenza, proporzione.",''),
(428,"ciclismo","Sport della bicicletta.",''),
(429,"bacchetta","Asticciola di legno o d'altra materia.",''),
(430,"acquistare","Ottenere la proprietà di un bene versando il corrispettivo in danaro.",''),
(431,"difesa","Protezione o salvaguardia diretta a respingere offese.",''),
(432,"pasticca","Pastiglia, caramellina.",''),
(433,"campeggiare","Soggiornare in un campeggio.",''),
(434,"scaffale","Elemento dell'arredamento.",''),
(435,"accaduto","Uno o più fatti, per lo più in quanto contenuto di una narrazione.",''),
(436,"sauna","Il caratteristico bagno a vapore.",''),
(437,"eccellenza","Qualità di sommo pregio o gradimento, unicità, perfezione.",''),
(438,"brillante","Emana o riflette una luce particolarmente splendente, sfavillante.",''),
(439,"vincere","Sconfiggere qualcuno.",''),
(440,"sfera","Figura geometrica solida racchiusa da una superficie curva.",''),
(441,"sguardo","L'atto del guardare.",''),
(442,"parlamento","Organo collegiale e rappresentativo della volontà politica dei cittadini.",''),
(443,"aggiungere","Unire a qualcosa che è già presente.",''),
(444,"continuo","Non interrotto nel tempo.",''),
(445,"nazione"," Collettività etnica di individui coscienti di essere legati da una comune tradizione.",''),
(446,"oscurare","Rendere qualcosa oscuro.",''),
(447,"nominale","Relativo all'uso o alla presenza del nome come categoria grammaticale.",''),
(448,"fumare","Emettere, produrre fumo.",''),
(449,"paladino","Cavaliere di alta nobiltà e valore.",''),
(450,"mouse","Dispositivo di puntamento per computer.",''),
(451,"nascita","L'inizio della partecipazione individuale all'esistenza.",''),
(452,"distanza","Spazio che separa fra loro due luoghi.",''),
(453,"cuccia","Giaciglio del cane.",''),
(454,"oceano","Termine che indica le più vaste distese acquee del globo.",''),
(455,"pendolare","Lavoratore o studente che si sposta dalla località di residenza per raggiungere la propria attività.",''),
(456,"abolito","Annullare, sopprimere qualcosa.",''),
(457,"pentacolo","Specie di amuleto a forma di stella a cinque punte.",''),
(458,"sereno","Del cielo azzurro sgombro di nubi.",''),
(459,"fratello","Persona legata ad altra o ad altre da un vincolo di parentela.",''),
(460,"scrittore","Chi scrive opere con intento artistico.",''),
(461,"penitenza","Sentimento di contrizione per aver commesso errori o colpe.",''),
(462,"abbracciare","Stringere con le braccia, per lo più in segno di affetto.",''),
(463,"soluzione","L'ottenimento di un risultato.",''),
(464,"odorare","Percepire con l'olfatto l'odore di qualcosa.",''),
(465,"reputazione","La considerazione altrui.",''),
(466,"asteroide","Corpi rocciosi in orbita solare.",''),
(467,"riprendere","Prendere, afferrare di nuovo.",''),
(468,"memoria","Capacità del cervello di conservare informazioni.",''),
(469,"pannolino","Piccola pezza di materiale assorbente, usata per l'igiene intima dei neonati.",''),
(470,"olfatto","Funzione sensoriale specifica relativa alla percezione degli odori.",''),
(471,"argomento","Tema od oggetto di una conversazione.",''),
(472,"pastorale","Relativo alla vita e ai costumi dei pastori.",''),
(473,"destinazione","Assegnazione decisa nell'ambito di un piano prestabilito.",''),
(474,"visitare","Recarsi presso qualcuno per intrattenersi con lui.",''),
(475,"palazzo","Edificio di notevole impegno e sviluppo architettonico, adibito ad abitazione.",''),
(476,"parlamentare","Membro del parlamento.",''),
(477,"pancreas","Ghiandola addominale annessa all'apparato digerente.",''),
(478,"cancellazione","Revoca, estinzione, annullamento.",''),
(479,"microfono","Apparecchio che trasforma onde sonore in segnali elettrici.",''),
(480,"biglietteria","Spazio adibito alla vendita di biglietti.",''),
(481,"ripetere","Effettuare di nuovo un'azione.",''),
(482,"pedante","Ostenta con presunzione il proprio sapere, spesso inconsistente.",''),
(483,"passaporto","Documento che dà facoltà al cittadino di uno stato di allontanarsi dal territorio nazionale.",''),
(484,"annunciare"," Far sapere qualcosa.",''),
(485,"navigazione","Attività del navigare sull'acqua con imbarcazioni, o anche nell'aria con aerei o nello spazio con veicoli spaziali.",''),
(486,"affrontare","Fronteggiare qualcuno con decisione o coraggio.",''),
(487,"organizzare","Formare, disporre, coordinare qualcosa.",''),
(488,"maestoso","Che s'impone all'attenzione o all'ammirazione per imponenza.",''),
(489,"oliva","Frutto dell'olivo.",''),
(490,"vario","Che è composto di elementi diversi l'uno dall'altro, ma non contrastanti.",''),
(491,"accanito","Rabbioso, furioso, inferocito.",''),
(492,"sufficienza","Ciò che basta a soddisfare una necessità.",''),
(493,"esprimere","Manifestare, esternare le proprie idee o i propri sentimenti.",''),
(494,"ricevere","Prendere, accogliere qualcosa che viene dato.",''),
(495,"scherzo","Atto o discorso privo di serietà o di impegno.",''),
(496,"tavola","Asse di legno di forma rettangolare, lunga, stretta e piuttosto sottile.",''),
(497,"pubblicare","Diffondere, rendere qualcosa di pubblica conoscenza.",''),
(498,"percorribile","Che si può percorrere.",''),
(499,"sostenere","Mantenere una persona in posizione eretta affinché non cada.",''),
(500,"bagagliaio","Scomparto della carrozzeria che serve per trasportare un carico all'interno del veicolo.",''),
(501,"straniero","Appartenente a un altro paese.",''),
(502,"odierno","Relativo alla giornata o anche all'epoca presente.",''),
(503,"minuto","Unità di misura dell'intervallo di tempo pari a 60 secondi.",''),
(504,"personaggio","Persona importante, per grado gerarchico o per fama.",''),
(505,"incidente","Accadimento inatteso che procura un danno.",''),
(506,"prenotazione","Fissare in precedenza qualcosa, farlo riservare per sé.",''),
(507,"montagna","Rilievo montuoso di particolare imponenza.",''),
(508,"accordo","Conformità di opinioni o intenzioni.",''),
(509,"risultato","Conclusione, effetto di un'azione.",''),
(510,"cattolico","Chi professa la religione cristiana cattolica.",''),
(511,"antenna","dispositivo elettrico atto a trasmettere o ricevere onde elettromagnetiche.",''),
(512,"sociale","Tendente a vivere in società.",''),
(513,"stufato","Cuocere un alimento a lungo e a fuoco lento.",''),
(514,"indicare","Fornire un'informazione con parole o gesti.",''),
(515,"dolciastro","i sapore piuttosto dolce, ma non gradevole.",''),
(516,"corso","Serie metodica di lezioni o trattazione sistematica di una disciplina.",''),
(517,"novembre","L'undicesimo mese dell'anno.",''),
(518,"scena","Parte del palcoscenico in cui gli attori recitano.",''),
(519,"semaforo","Impianto per la regolazione del traffico stradale.",''),
(520,"situazione","Condizione, in cui si trova una cosa o una persona.",''),
(521,"incrocio","Punto d'intersezione di due elementi.",''),
(522,"orologeria","La fabbricazione o l'industria degli orologi.",''),
(523,"omologo","Che ha le stesse caratteristiche di un altro.",''),
(524,"taglierino","Utensile di piccole dimensioni utilizzato per tagliare.",''),
(525,"orientare","Volgere qualcosa verso un punto cardinale.",''),
(526,"oltraggio","Offesa grave e consapevole contro l'onore o la dignità di qualcuno.",''),
(527,"pagliacciata","Messinscena clamorosa, offensiva del buon gusto.",''),
(528,"riservato","Destinato esclusivamente ad alcune persone o ad alcuni usi.",''),
(529,"accendisigari","Macchinetta a benzina o a gas liquido, per accendere sigari o sigarette.",''),
(530,"uccidere","Privare della vita una persona o un animale.",''),
(531,"viola","Pianta erbacea delle Violacee.",''),
(532,"abbattono","Buttare giù, far cadere.",''),
(533,"riscaldamento","Apporto di calore a un materiale, a un corpo, a un ambiente.",''),
(534,"regno","Stato monarchico.",''),
(535,"apparecchiare","Preparare ordinatamente qualcosa.",''),
(536,"pennello","Attrezzo costituito da un ciuffo di peli naturali o sintetici.",''),
(537,"simile","Affinità, somiglianza o analogia con un altro oggetto.",''),
(538,"nervoso","Caratterizzato da continue variazioni, instabile.",''),
(539,"adocchio","Guardare con particolare interesse o desiderio.",''),
(540,"frenare","Rallentare un corpo in movimento.",''),
(541,"stringere","Avvicinare tra loro due cose o parti della stessa cosa.",''),
(542,"stagione","Ognuno dei quattro periodi in cui è diviso l'anno.",''),
(543,"nervosismo","Senso diffuso e pungente di irritazione e scontento.",''),
(544,"formato","Costituito, composto.",''),
(545,"libero","Non soggetto a padrone o a qualsiasi forma di dominio.",''),
(546,"disposizione","Collocazione o distribuzione funzionale.",''),
(547,"raggiungere","Toccare un certo luogo, arrivarvi.",''),
(548,"mestiere","Attività esercitata abitualmente.",''),
(549,"indovinato","Previsto, pronosticato.",''),
(550,"formare","Realizzare dando una forma, modellare.",''),
(551,"odiare","Provare ostilità verso qualcuno.",''),
(552,"occhiale","Ogni strumento ottico che migliora la vista.",''),
(553,"abusato","Usato senza misura né criterio e spesso a sproposito.",''),
(554,"accentuare","Rendere più marcato.",''),
(555,"osare","Avere il coraggio di compiere un'azione difficilissima o rischiosa.",''),
(556,"spilla","Oggetto, spesso prezioso, che si appunta mediante uno spillo su vestiti.",''),
(557,"adagio","Con lentezza, piano.",''),
(558,"settimana","Periodo di sette giorni.",''),
(559,"generale","Di tutti gli appartenenti a un genere, a una categoria, ad essi comune.",''),
(560,"allarme","Dispositivo d'emergenza che avverte di un pericolo.",''),
(561,"tedesco","Appartenente, relativo alla Germania.",''),
(562,"opprimere","Premere col proprio peso, gravare.",''),
(563,"autunno","La terza stagione dell'anno.",''),
(564,"grattugia","Strumento da cucina utilizzato per ridurre in briciole.",''),
(565,"esperienza","Conoscenza acquisita attraverso il contatto diretto con la realtà.",''),
(566,"ospedale","Istituto pubblico o privato destinato all'assistenza sanitaria.",''),
(567,"quarto","In una successione ordinata, occupa il posto corrispondente al numero 4.",''),
(568,"questione","Problema, caso da esaminare e risolvere.",''),
(569,"abbronzata","Di colore bronzeo.",''),
(570,"passato","Non più attuale, superato.",''),
(571,"serbatoio","Qualsiasi cavità o recipiente adibito a contenere o conservare liquidi.",''),
(572,"negoziante","Proprietario o gestore di un negozio.",''),
(573,"relazione","Resoconto, esposizione orale o scritta di un dato argomento.",''),
(574,"ritardo","Azione e risultato del ritardare.",''),
(575,"patente","Documento di autorizzazione all'esercizio di una determinata attività.",''),
(576,"accentravo","Riunire nello stesso luogo.",''),
(577,"satellite","Qualsiasi corpo celeste che ruoti attorno a un pianeta.",''),
(578,"metro","Unità fondamentale di misura di lunghezza.",''),
(579,"quadro","Elemento o superficie di forma quadrata.",''),
(580,"impressione","Qualsiasi forma di esperienza conoscitiva o emotiva.",''),
(581,"bollitore","Recipiente domestico per far bollire liquidi vari.",''),
(582,"nudista","Pratica naturista favorevole all'abolizione dei vestiti.",''),
(583,"narrazione","Esposizione di un racconto.",''),
(584,"pecorino","Prodotto o ricavato dalla pecora.",''),
(585,"osceno","Che offende la moralità in campo sessuale.",''),
(586,"pelato","Privo di peli.",''),
(587,"adiacente","Che si trova vicino.",''),
(588,"acclamare","Eleggere qualcuno a gran voce, applaudendo.",''),
(589,"preciso","Ben determinato, stabilito con esattezza.",''),
(590,"abusare","Fare un uso eccessivo o arbitrario di qualcosa.",''),
(591,"intermedio","Compreso tra due punti di riferimento nello spazio o nel tempo.",''),
(592,"pendere","Essere appeso o attaccato a un sostegno posto in alto.",''),
(593,"gruppo","Insieme di persone o cose distinte ma riunite in un unico complesso.",''),
(594,"comune","Un comune è un ente territoriale di base.",''),
(595,"mantenere","Rimanere in una certa condizione.",''),
(596,"odissea","Serie di fatti o di avvenimenti infausti e dolorosi.",''),
(597,"notturno","Pertinente alla notte.",''),
(598,"accademico","Pertinente o relativo a un'accademia.",''),
(599,"dentifricio","Preparato cosmetico ad azione detersiva per la pulizia dei denti.",''),
(600,"riserva","il mettere da parte qualcosa per utilizzarlo in futuro.",''),
(601,"condurre","Guidare, pilotare un mezzo di trasporto.",''),
(602,"accidente","Ciò che accade, caso, combinazione.",''),
(603,"attraversare","Percorrere da un lato a quello opposto.",''),
(604,"accortezza","Perspicacia, prontezza d'intuito, astuzia.",''),
(605,"figurare","Fare bella figura, impressionare favorevolmente.",''),
(606,"paralisi","Perdita della mobilità e della sensibilità di uno o più arti o parti del corpo.",''),
(607,"patente","Documento di autorizzazione all'esercizio di una determinata attività.",''),
(608,"pennellare","Colorare o verniciare qualcosa.",''),
(609,"campagna","Terreno aperto, coltivato o incolto.",''),
(610,"acerbo","Non ancora maturo.",''),
(611,"accenno","Avviso, avvertimento, leggero indizio.",''),
(612,"corridoio","Ambiente sul quale si affacciano vari locali o stanze.",''),
(613,"giusto","Di persona che conforma i propri giudizi e comportamenti a criteri di equità.",''),
(614,"oppressione","Sopraffazione da parte di un potere.",''),
(615,"attuale","Presente, odierno.",''),
(616,"casseruola","Utensile da cucina.",''),
(617,"principe","Il più alto dei titoli nobiliari.",''),
(618,"orsacchiotto","Cucciolo di orso.",''),
(619,"griglia","Struttura in metallo a barre parallele e perpendicolari tra di loro.",''),
(620,"abbaiare","Verso caratteristico del cane.",''),
(621,"vacanza","Periodo di libertà dal lavoro o dagli obblighi scolastici.",''),
(622,"conoscenza","Consapevolezza e la comprensione di fatti.",''),
(623,"nudismo","Atteggiamento in favore della soppressione del vestiario.",''),
(624,"pinze","Utensile in metallo usato per afferrare, stringere e tagliare.",''),
(625,"fissare","Collocare o applicare stabilmente, rendere fisso.",''),
(626,"ufficiale","Emanato dall'autorità o dall'organo competente.",''),
(627,"nocciola","Frutto e il seme dell'albero del nocciolo.",''),
(628,"costituire","Fondare, creare, istituire.",''),
(629,"svegliare","Far uscire dal sonno.",''),
(630,"difendere","Proteggere qualcuno o qualcosa.",''),
(631,"lezione","Attività didattica svolta da un docente con uno o più allievi in un tempo determinato.",''),
(632,"generale","Comune o applicabile a un intero ordine di fatti.",''),
(633,"pastiera","Torta a base di pasta frolla.",''),
(634,"targa","Placca di metallo o altro materiale su cui sono scritti nomi, numeri, indicazioni varie.",''),
(635,"prenotare","Fissare in anticipo qualcosa.",''),
(636,"mattone","Materiale a forma di parallelepipedo, usato nella costruzione di murature.",''),
(637,"modifica","Parziale trasformazione, cambiamento di qualcosa.",''),
(638,"calendario","Sistema di divisione del tempo basato su fenomeni astronomici.",''),
(639,"paesaggio","Il paesaggio è la particolare fisionomia di un territorio.",''),
(640,"risultare","Conclusione, effetto di un'azione.",''),
(641,"spingere","Premere un oggetto per abbassarlo.",''),
(642,"rifiutare","Non accettare, respingere qualcuno.",''),
(643,"avvitare","Introdurre e serrare una vite.",''),
(644,"passatempo","Mezzo o motivo di ricreazione o di divertimento.",''),
(645,"abituato","Che ha ricevuto una determinata educazione.",''),
(646,"microfono","Apparecchio che trasforma onde sonore in segnali elettrici.",''),
(647,"posteriore","Che sta dietro, retrostante.",''),
(648,"giugno","Il sesto mese dell'anno.",''),
(649,"ormone","Ciascuna delle sostanze organiche, prodotte dalle ghiandole endocrine.",''),
(650,"secchio","Recipiente piuttosto capace, di forma cilindrica.",''),
(651,"abbaio","Il verso del cane.",''),
(652,"abolizione","Cessazione definitiva imposta d'autorità.",''),
(653,"coperta","Qualsiasi panno di adeguate dimensioni, che serva a coprire e riparare dal freddo.",''),
(654,"solito","Conforme alla consuetudine.",''),
(655,"complesso","Che presenta difficoltà per la comprensione.",''),
(656,"visita","Atto di andare a trovare, a visitare qualcuno.",''),
(657,"appartenere","Essere legittima proprietà di qualcuno.",''),
(658,"elemento","Sostanza semplice di cui sono formati i corpi.",''),
(659,"ingrediente","Ogni sostanza che, insieme con altre, compone un miscuglio.",''),
(660,"segreto","Condizione o luogo riservato, intimo.",''),
(661,"prossimo","Molto vicino a qualcuno o a qualcosa.",''),
(662,"nucleo","La porzione centrale, la più interna di qualcosa.",''),
(663,"forchetta","Posata per portare i cibi alla bocca.",''),
(664,"principio","Momento iniziale, origine, punto di avvio o di partenza.",''),
(665,"mercato","Il luogo in cui avvengono le contrattazioni.",''),
(666,"trasformare","Rendere completamente diverso nell'aspetto.",''),
(667,"ammettere","Accettare, approvare, permettere qualcosa.",''),
(668,"pasticcio","Situazione intricata, complicata, difficilmente risolvibile.",''),
(669,"autolavaggio","Area opportunamente attrezzata per il lavaggio di automobili.",''),
(670,"svitare","Estrarre una vite girandola in senso inverso a quello in cui è stata avvitata.",''),
(671,"vigile","Accorto, assiduamente attento e sollecito.",''),
(672,"omosessuale","L'individuo eroticamente attratto da soggetti del proprio sesso.",''),
(673,"orrore","Forte sensazione di ribrezzo, moto di repulsione",''),
(674,"ascoltare","Udire attentamente qualcuno.",''),
(675,"pastiglia","Preparazione farmaceutica costituita da polveri o da impasti.",''),
(676,"operazione","L'azione che si determina come fatto tecnico o pratico.",''),
(677,"conducente","Chi guida un veicolo a trazione animale o meccanica.",''),
(678,"ottimizzare","Portare qualcosa alle condizioni ottimali.",''),
(679,"preoccupare","Pensiero o motivo di apprensione.",''),
(680,"interno","Che si trova dentro a qualcosa.",''),
(681,"abbellisca","Rendere più bello mediante ornamenti.",''),
(682,"ritenere","Avere una certa opinione personale su qualcuno o qualcosa.",''),
(683,"direzione","Linea ideale lungo la quale muove una persona.",''),
(684,"ricordo"," L'atto, il fatto di ricordare una persona o una cosa.",''),
(685,"gomma","Sostanza naturale derivante dal latice di alcune piante.",''),
(686,"intendere","Capire, comprendere qualcosa.",''),
(687,"cambiare","Sostituire una cosa o una persona con un'altra dello stesso genere.",''),
(688,"sinistro","Situato dalla parte corrispondente alla posizione del cuore.",''),
(689,"offerente","Chi fa un'offerta.",''),
(690,"nostalgia","Sentimento malinconico che si prova nel rimpiangere cose e tempi ormai trascorsi.",''),
(691,"ferrovia","Percorso costituito da binari su cui circolano i treni.",''),
(692,"occulto","Che non è visibile o non è percepibile intellettualmente.",''),
(693,"desiderio","Sentimento di ricerca appassionata o di attesa del possesso.",''),
(694,"affare","Cosa di una certa importanza che si fa o si è fatta o è da farsi.",''),
(695,"pedofilo","Che manifesta pedofilia.",''),
(696,"finestrino","Finestra di un mezzo di trasporto.",''),
(697,"cambio","Apparecchio che serve a variare la velocità in una trasmissione fra un albero conduttore e un condotto.",''),
(698,"decoro","Decoroso.",''),
(699,"ostacolo","Qualsiasi cosa o persona che intralcia o costituisce una difficoltà allo svolgimento di un'azione.",''),
(700,"capotreno","Il capo del personale in servizio su un convoglio ferroviario.",''),
(701,"cavatappi","Strumento a vite o a leva per estrarre il tappo di sughero dalle bottiglie o dai fiaschi.",''),
(702,"parrocchia","Ciascuna delle circoscrizioni territoriali in cui è suddivisa una diocesi ecclesiastica.",''),
(703,"programmare","Avere intenzione di fare qualcosa, mettere in programma.",''),
(704,"orientamento","La determinazione della posizione o della direzione.",''),
(705,"nubile","Donna non coniugata.",''),
(706,"automatico","Che funziona senza l'intervento dell'uomo",''),
(707,"accellerata","Rapida accelerazione del motore.",''),
(708,"privato","Considerato solo come persona, fuori dal ruolo sociale e dalla funzione pubblica.",''),
(709,"ciotola","Ampia tazza emisferica.",''),
(710,"ottica","Modo di considerare, inquadrare, classificare.",''),
(711,"abbocco","Detto dei pesci, afferrare l'esca.",''),
(712,"atterrare","Gettare qualcosa a terra.",''),
(713,"architetto","Chi progetta la costruzione, il restauro o l'arredo di edifici.",''),
(714,"ortodosso","Rigido osservante di un principio.",''),
(715,"grigliare","Cuocere sulla griglia.",''),
(716,"posto","Porzione di spazio in cui è abitualmente collocata una cosa.",''),
(717,"problema","Quesito che attende una soluzione.",''),
(718,"emergenza","Circostanza imprevista.",''),
(719,"anatra","Nome di diverse varietà di uccelli acquatici con becco largo e piatto e piedi palmati.",''),
(720,"monaca","Donna consacrata a Dio ",''),
(721,"impedire","Rendere impossibile, vietare qualcosa.",''),
(722,"cucchiaio","Pezzo della posateria, usato per portare alla bocca cibi liquidi o semiliquidi.",''),
(723,"omaggio","Atto o professione di ossequio o di rispetto.",''),
(724,"marciapiede","Parte della strada riservata al passaggio dei pedoni.",''),
(725,"compiere","Portare a termine, finire, concludere.",''),
(726,"milione","Nel sistema decimale, unità del settimo ordine corrispondente a mille migliaia.",''),
(727,"passera","Nome comune di vari Uccelli Passeriformi.",''),
(728,"ottico","Relativo alla vista e all'apparato visivo dell'uomo.",''),
(729,"tessera"," Cartoncino rettangolare o libretto che riporta i dati anagrafici.",''),
(730,"abissi","Baratri, voragini.",''),
(731,"pitturare","Verniciare qualcosa.",''),
(732,"storico","Relativo alla storia.",''),
(733,"termine","Parola o locuzione propria di un ambito definito.",''),
(734,"industriale","Dell'industria, relativo all'industria.",''),
(735,"onorevole","Titolo attribuito ai membri del parlamento.",''),
(736,"passeggiata","Camminata agevole fatta per svago e passatempo.",''),
(737,"spazzatura","Materiale di rifiuto, immondizia.",''),
(738,"spiedo","Asta appuntita di ferro in cui si infilzano carni.",''),
(739,"bocca","Cavità corrispondente all'inizio del canale alimentare.",''),
(740,"partigiano","combattente armato che non appartiene ad un esercito regolare.",''),
(741,"americano","chi abita negli Stati Uniti d'America.",''),
(742,"accampato","Sistemare qualcuno in alloggiamenti.",''),
(743,"ottone","Lega inossidabile di rame e zinco, di colore giallo.",''),
(744,"furgoncino","Veicolo di piccole dimensioni, completamente chiuso.",''),
(745,"rubinetto","Dispositivo che, applicato all'estremità di una tubatura regola l'afflusso del fluido.",''),
(746,"rivolgere","Volgere qualcosa- verso una certa direzione.",''),
(747,"provocare","Spingere a un sentimento negativo o a un comportamento aggressivo.",''),
(748,"salutare","Che reca giovamento alla salute.",''),
(749,"participio","Modo verbale molto vicino all'aggettivo e al sostantivo.",''),
(750,"persona","L'individuo umano in quanto oggetto di considerazione.",''),
(751,"adoperare","Fare uso di qualcosa per uno scopo ben preciso.",''),
(752,"pastina","Pasta alimentare di forme molto piccole.",''),
(753,"zerbino","Piccolo tappeto rettangolare.",''),
(754,"delizioso","Attraente per la delicatezza, la raffinatezza, l'eleganza.",''),
(755,"accanire","Ostinato, tanto nel male che nel bene.",''),
(756,"domandare","Chiedere a qualcuno per un'informazione.",''),
(757,"sicurezza","Cautela contro eventualità spiacevoli.",''),
(758,"vernice","Soluzione a base di resine naturali o sintetiche, che, stesa su una superficie, lascia una patina lucida.",''),
(759,"coscienza","Capacità dell'uomo di riflettere su se stesso.",''),
(760,"tappeto","Sorta di tessuto grosso e compatto, di lana o di fibre vegetali.",''),
(761,"negoziare","Fare oggetto di contrattazione.",''),
(762,"nobile","Che appartiene, per nascita o per privilegio acquisito, a una classe sociale superiore.",''),
(763,"gettare","isfarsi di ciò che non serve più.",''),
(764,"intermezzo","Intervallo nel corso di uno spettacolo.",''),
(765,"orbita","Traiettoria nello spazio di un corpo naturale.",''),
(766,"occidentale","Situato a ovest, proveniente da ovest.",''),
(767,"forma","Aspetto esteriore di un oggetto.",''),
(768,"destino","L'insieme imponderabile delle cause che si pensa abbiano determinato gli eventi della vita.",''),
(769,"orizzonte","La linea apparente, circolare, che segna i confini della visibilità a partire da un luogo d'osservazione.",''),
(770,"maggio","Quinto mese dell'anno.",''),
(771,"macchina","Congegno meccanico ideato per compiere un lavoro.",''),
(772,"igiene","Branca della medicina che studia le modalità più opportune per conservare la salute e prevenire malattie.",''),
(773,"diventare","Acquistare una qualità, una condizione o un ruolo diversi dai precedenti.",''),
(774,"occidente"," La parte di orizzonte dove tramonta il sole.",''),
(775,"europeo","Abitante, originario o nativo dell'Europa.",''),
(776,"pendenza","Grado di ripidità o di inclinazione di una strada o di un tratto di percorso.",''),
(777,"abbronzato","Che ha preso il colore del bronzo per esposizione al sole.",''),
(778,"estremo","Ultimo nello spazio.",''),
(779,"consentire","Permettere, concedere qualcosa.",''),
(780,"estate","La seconda stagione dell'anno.",''),
(781,"istante","Momento brevissimo.",''),
(782,"valore","Complesso delle doti e capacità.",''),
(783,"opponibile","Che può essere opposto o contrapposto.",''),
(784,"misurare","Determinare il valore di una grandezza fisica con l'impiego di uno strumento di misura.",''),
(785,"personale","Riguardante la persona.",''),
(786,"passare","Andare da un punto a un altro percorrendo uno spazio.",''),
(787,"considerare","Esaminare con attenzione un problema teorico.",''),
(788,"partecipante","Che partecipa, prende parte a qualcosa.",''),
(789,"novella","Narrazione di solito breve, perlopiù in prosa, di fatti reali o immaginari.",''),
(790,"fianco","La parte laterale dell'addome.",''),
(791,"accadere","Succedere, capitare.",''),
(792,"accecare","Rendere cieco, privare del senso o dell'uso della vista.",''),
(793,"permettere","Dare il permesso di fare qualcosa.",''),
(794,"programma","Insieme organizzato di istruzioni redatte organicamente secondo un determinato linguaggio.",'');